<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="section-subscribe">
	<h3 class="title">
	    <span>Newsletter</span>
	</h3>
	<div class="block newsletter">
	    <div class="title"><strong>Newsletter</strong></div>
	    <p>Sign up to our newsletter for all the latest news, special offers and new products&hellip;</p>
	    <div class="content">
	        <form class="form subscribe"
	            novalidate
	            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
	            method="post"
	            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
	            id="newsletter-validate-detail">
	            <div class="field newsletter">
	                <label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Our Newsletter:') ?></span></label>
	                <div class="control">
	                    <input name="email" type="email" id="newsletter"
	                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
	                                data-validate="{required:true, 'validate-email':true}"/>
	                </div>
	            </div>
	            <div class="actions">
	                <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
	                    <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
	                </button>
	            </div>
	        </form>
	    </div>
	</div>
</div>