<div class="copyright">
    <div class="page-main clearfix">
        <ul class="links">
            <li><img src="<?php echo $this->getViewFileUrl('images/secure-payment.png'); ?>" class="image" /></li>
            <li><img src="<?php echo $this->getViewFileUrl('images/icons/payment-icons.png'); ?>" class="payment-icons" /></li>
        </ul>
        <span class="message">Copyright &copy; <?php echo date("Y"); ?> Stonegate. All Rights Reserved.</span>
    </div>
</div>