<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$dataHelper = $this->helper("Lof\RequestForQuote\Helper\Data");
$enable_quote = $dataHelper->isEnabledQuote();
$enable_addtoquote_nonsale = $dataHelper->getConfig('general/enable_addtoquote_nonsale');
$enable_addtoquote_nonsale = ($enable_addtoquote_nonsale !== null) ? (int)$enable_addtoquote_nonsale : 0;
$disable_addtocart = $dataHelper->getConfig('general/disable_addtocart');
$disable_addtocart = ($disable_addtocart !== null) ? (int)$disable_addtocart : 0;
$enable_addtoquote = $dataHelper->getConfig('general/enable_addtoquote');
$enable_addtoquote = ($enable_addtoquote !== null) ? (int)$enable_addtoquote : 1;
$enable_addtoquote_category = $dataHelper->getConfig('general/enable_addtoquote_category');
$enable_addtoquote_category = ($enable_addtoquote_category !== null) ? (int)$enable_addtoquote_category : 1;
//$disable_addtocart = 1;

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */
    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
    echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php 
                    $is_disable_addtocart = $dataHelper->isDisabledAddTocart($_product);
                    $is_enable_addtoquote = $dataHelper->isEnabledAddToQuote($_product, $enable_addtoquote_category);
                ?>
                <?php /* @escapeNotVerified */
                echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */
                    echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */
                               echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */
                                echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */
                        echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable() || ($enable_addtoquote_nonsale && !$_product->isSaleable())): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                        echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */
                                            echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */
                                            echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                   value="<?php /* @escapeNotVerified */
                                                   echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey') ?>
                                            <?php if ($is_disable_addtocart) {
                                                //Do nothing at here
                                            } elseif ($_product->isSaleable()) {
                                                ?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo __('Add to Cart') ?></span>
                                                </button>
                                            <?php } ?>
                                            <?php if ($is_enable_addtoquote) { ?>
                                                <?php $buttonTitle = __('Add to Quote'); ?>

                                                <button type="submit"
                                                        title="<?php /* @escapeNotVerified */
                                                        echo $buttonTitle ?>"
                                                        class="action primary toquote product-addtoquote-button">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo $buttonTitle ?></span>
                                                </button>

                                            <?php } ?>

                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */
                                                    echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                    echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links"
                                     class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription): ?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */
                                    echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */
                                    echo $_productNameStripped ?>"
                                       class="action more"><?php /* @escapeNotVerified */
                                        echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if ($enable_quote && $enable_addtoquote_category) { ?>
        <script>
            require([
                'jquery',
                'mage/mage',
                'Magento_Catalog/js/catalog-add-to-cart',
                'Lof_RequestForQuote/js/catalog-add-to-quote'
            ], function ($) {
                'use strict'
                var addToQuote = false;


                $('.product-addtoquote-button').each(function () {

                    $(this).on("click", function () {
                        addToQuote = $(this).closest('form[data-role=tocart-form]').attr('action').replace("checkout/cart/add", "quotation/cart/add");

                    });

                    $(this).next().on("click", function () {
                        var addToQuote = false;
                    });
                    $(this).closest('form[data-role=tocart-form]').mage('validation', {
                        radioCheckboxClosest: '.nested',
                        submitHandler: function (form) {
                            if (addToQuote) {
                                var widget = $(form).catalogAddToQuote({
                                    bindSubmit: false,
                                    quoteFormUrl: addToQuote
                                });
                                widget.catalogAddToQuote('submitForm', $(form));
                                addToQuote = false;
                            } else {
                                var widget = $(form).catalogAddToCart({bindSubmit: false});
                                widget.catalogAddToCart('submitForm', $(form));
                            }
                            return false;
                        }
                    });
                });
            });


        </script>
    <?php } else { ?>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?php /* @escapeNotVerified */
                echo $_product->getSku() ?>"
                }
            }
        }

            </script>
        <?php endif; ?>
    <?php } ?>
<?php endif; ?>



