<?php

$helper = $this->helper("Lof\RequestForQuote\Helper\Data");
$enable = $helper->isEnabledQuote();
$disable_qty = $helper->getConfig('general/disable_qty');
$disable_qty = ($disable_qty !== null) ? (int)$disable_qty : 0;
$disable_addtocart = $helper->getConfig('general/disable_addtocart');
$disable_addtocart = ($disable_addtocart !== null) ? (int)$disable_addtocart : 0;
$enable_addtoquote = $helper->getConfig('general/enable_addtoquote');
$enable_addtoquote = ($enable_addtoquote !== null) ? (int)$enable_addtoquote : 1;

$item = $block->getItem();
$product = $item->getProduct();
$is_disable_addtocart = $helper->isDisabledAddTocart($product);
?>
<?php foreach ($block->getChildNames() as $childName): ?>
    <?= /* @noEscape */
    $block->getLayout()->renderElement($childName, false) ?>
<?php endforeach; ?>

<?php
    if ($is_disable_addtocart) {
?>
<div class="box-tocart">
    <fieldset class="fieldset">
        <?php if ($item->canHaveQty() && $product->isVisibleInSiteVisibility() && !$disable_qty): ?>
            <div class="field qty">
                <label class="label"
                       for="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                <div class="control">
                    <input type="number" data-role="qty" id="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]"
                           class="input-text qty"
                           data-validate="{'required-number':true,'validate-greater-than-zero':true}"
                           name="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]" value="<?= /* @noEscape */
                    (int)($block->getAddToCartQty($item) * 1) ?>">
                </div>
            </div>
        <?php endif; ?>
        <?php if ($product->isSaleable()): ?>
            <div class="product-item-actions">
                <div class="actions-primary">
                    <button type="button" data-role="tocart" data-post='<?= /* @noEscape */
                    $block->getItemAddToCartParams($item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                            data-item-id="<?= $block->escapeHtmlAttr($item->getId()) ?>" class="action tocart primary">
                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                    </button>
                </div>
            </div>
        <?php else: ?>
            <?php if ($product->getIsSalable()): ?>
                <p class="available stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $block->escapeHtml(__('In stock')) ?></span>
                </p>
            <?php else: ?>
                <p class="unavailable stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                </p>
            <?php endif; ?>
        <?php endif; ?>
    </fieldset>
</div>

<?php } ?>