<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit */
$_item = $block->getItem();
$useForQuote = $_item->getQuote()->getUseForQuotation();
?>
<?php if( (int)$useForQuote !== 1 ){ ?>
    <?php if ($block->isProductVisibleInSiteVisibility()): ?>
        <a class="action action-edit"
        href="<?= /* @escapeNotVerified */ $block->getConfigureUrl() ?>"
        title="<?= $block->escapeHtml(__('Edit item parameters')) ?>">
            <span>
                <?= /* @escapeNotVerified */ __('Edit') ?>
            </span>
    </a>
    <?php endif ?>
<?php } ?>
