<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base">Request Your <span class="highlight">Free</span> Copy of the Diamond Book</span>
    </h1>
</div>
<div class="column-container">
    <div class="column-1-3">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('request_catalogue_description')->toHtml(); ?>
    </div>
    <div class="column-2-3">
        <form accept-charset="UTF-8" action="<?php echo $block->getUrl('requestcatalogue/index/post'); ?>" class="register-product" id="form_requestcatalogue" method="post">
            <fieldset class="fieldset">
                <div class="fields">
                    <div class="field">
                        <label class="label" for="first-name">First Name<abbr title="required">*</abbr></label>
                        <input type="text" placeholder="First name" id="first-name" required="required" name="form[first_name]" />
                    </div>
                    <div class="field">
                        <label class="label" for="last-name">Last Name<abbr title="required">*</abbr></label>
                        <input type="text" placeholder="Last name" id="last-name" required="required" name="form[last_name]" />
                    </div>
                    <div class="field">
                        <label class="label" for="company">Company<abbr title="required">*</abbr></label>
                        <input type="tel" placeholder="Company" id="company" required="required" name="form[company]" />
                    </div>
                    <div class="field">
                        <label class="label" for="phone-number">Phone Number<abbr title="required">*</abbr></label>
                        <input type="tel" placeholder="Tel no." id="phone-number" required="required" name="form[phone_number]" />
                    </div>
                    <div class="field">
                        <label class="label" for="last-name">Address<abbr title="required">*</abbr></label>
                        <input type="text" placeholder="Address" id="address" required="required" name="form[address]" />
                    </div>
                    <div class="field">
                        <label class="label" for="town-city">Town/City<abbr title="required">*</abbr></label>
                        <input type="text" placeholder="Town/City" id="town-city" required="required" name="form[town_city]" />
                    </div>
                    <div class="field">
                        <label class="label" for="postcode">Postcode<abbr title="required">*</abbr></label>
                        <input type="text" placeholder="Postcode" id="postcode" required="required" name="form[postcode]" />
                    </div>
                    <div class="field">
                        <label class="label" for="website">Website<abbr title="required">*</abbr></label>
                        <input type="text" placeholder="Website" id="website" required="required" name="form[website]" />
                    </div>
                </div>
            </fieldset>
            <button type="submit" title="Submit" class="action submit primary large">
                <span>Send Request</span>
            </button>
        </form>
    </div>
</div>
<div class="page-title-wrapper request-catalogue-download">
    <h1 class="page-title">
        <span class="base">Can't Wait? Download a Copy Now!</span>
    </h1>
</div>
<div class="column-container request-catalogue-download">
    <div class="column-1-3">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('download_catalogue_description')->toHtml(); ?>
        <a class="adobe" href="https://get.adobe.com/uk/reader/">
            <img src="<?php echo $this->getViewFileUrl('images/adobe-reader.jpg'); ?>" />
        </a>
    </div>
    <div class="column-2-3">
        <form accept-charset="UTF-8" action="<?php echo $block->getUrl('requestcatalogue/index/download'); ?>" class="register-product" id="form_requestcatalogue" method="post">
            <fieldset class="fieldset">
                <div class="fields">
                    <div class="field">
                        <label class="label" for="first-name">First Name<abbr title="required">*</abbr></label>
                        <input type="text" placeholder="First name" id="first-name" required="required" name="form[first_name]" />
                    </div>
                    <div class="field">
                        <label class="label" for="last-name">Last Name<abbr title="required">*</abbr></label>
                        <input type="text" placeholder="Last name" id="last-name" required="required" name="form[last_name]" />
                    </div>
                    <div class="field">
                        <label class="label" for="phone-number">Phone Number<abbr title="required">*</abbr></label>
                        <input type="tel" placeholder="Tel no." id="phone-number" required="required" name="form[phone_number]" />
                    </div>
                    <div class="field">
                        <label class="label" for="email-address">Email Address<abbr title="required">*</abbr></label>
                        <input type="email" placeholder="Email Address" id="email-address" required="required" name="form[email_address]" />
                    </div>
                </div>
            </fieldset>
            <button type="submit" title="Submit" class="action submit primary large">
                <span>Download Now</span>
            </button>
        </form>
    </div>
</div>