<div class="page-main culture section">
    <h2 class="title">Our Culture</h2>
    <h4 class="subtitle">We delight in being a culture driven business. Many people say it, but we mean it! </h4>
    <div class="description divider">All our teams are highly-trained and seriously put through their paces to ensure they can deliver true value to our customers. We strive for continual business improvement, adding value for all our stakeholders, employees, suppliers and, of course, customers.  We like to look at the qualities of culture for our business and work hard to make sure that every part of Stonegate conveys our mission and values.</div>
    <div class="description">There are some key qualities of our business that make it a truly great culture to work in:</div>
    <div class="column-container colspan-2">
        <div class="column">
            <div class="heading">Collaboration</div>
            <p>Working collaboratively is essential to the way we do business here, we relish in joint working partnerships both internally and externally. Our customers need us to speak their language and we endeavour to be technically-minded and being able to help in any way we can; keeping our customers in business is essential.</p>
            <div class="heading">Innovation</div>
            <p>We operate in a demanding industry, stone suppliers are always advancing the market with new materials and we work hard to bring our customers products that can cope. It’s not only about ‘new’ for this reason, however, we have a duty to bring products to our range which reduce downtime, increase efficiency, product finish and have increased life. As market leaders, innovation is what keeps us on top. </p>
            <div class="heading">Agility</div>
            <p>We exist in an industry that changes all the time. At Stonegate, we need to be agile in our approach, without losing momentum or vision. Our highly-trained team are adaptive and flexible and can cope with the demands of our customers.</p>
        </div>
        <div class="column">
            <div class="heading">Communication</div>
            <p>Communication is everything and our open and honest culture facilitate’s both internal and external communication effectively. We believe the only way to do business is to be open and honest.</p>
            <div class="heading">Work Environment, Support & Wellness</div>
            <p>We’re passionate about creating a working environment that works for everyone. We encourage working flexibility, getting out and interacting with our products in our testing workshop, enjoying our breakout areas or simply taking a break by using the gym or playing some table tennis. We support our staff both at work and home and it’s a mission of ours to ensure that each member of the team is happy and healthy – even to the extent of making sure everyone gets a lovely lunch!</p>
            <div class="heading">Responsibility</div>
            <p>The cornerstone of our business is trust. Every member of the team is employed based on their ability to perform well and be trusted to make key decisions in a professional and capable way. Our customers come to us for advice and guidance, we’re not like your average supplier, and, in that sense, we need to have the technical knowledge to responsibly dispense advice and ensure we keep our customers in business.</p>
        </div>
    </div>
</div>