<div class="fullwidth section director-comment">
    <div class="page-main">
        <div class="director-photo">
            <img src="<?php echo $this->getViewFileUrl('images/about/graham-hazell.png'); ?>" alt="Graham Hazel, Director" />
        </div>
        <div class="text-container">
            <div class="quote">“Welcome to Stonegate Precision Tooling, it’s important to us that you get to know your leading supplier; we’re here to ensure we exceed in delivering true excellence and we do that through a solid foundation and staying true to our values.”</div>
            <img src="<?php echo $this->getViewFileUrl('images/about/graham-name-text.svg'); ?>" class="name-text" />
            <div class="role">Director</div>
        </div>
    </div>
</div>