<div class="page-main history">
    <div class="top-text">
        <h2 class="title">Company History</h2>
        <div class="description">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('company_history')->toHtml(); ?>
        </div>
    </div>
    <div class="timeline section">
        <div class="start">
            <div class="title">Stonegate Founded</div>
            <div class="sub">1985</div>
        </div>
        <div class="dates">
            <div class="column"></div>
            <div class="column date first">
                <div class="icon">
                    <i class="fa fa-arrow-up" aria-hidden="true"></i>
                </div>
                <div class="text">
                    <div class="sub">1992</div>
                    <div class="title">We shifted focus & thought bigger</div>
                    <div class="description">Following our experience gained through understanding local contractors, we honed our focus to stone fabricating and moved to larger premises to offer our value-added service nationwide.</div>
                </div>
            </div>
            <div class="column date left">
                <div class="icon">
                    <i class="fa fa-users" aria-hidden="true"></i>
                </div>
                <div class="text">
                    <div class="sub">2004</div>
                    <div class="title">A change in leadership</div>
                    <div class="description">Following a steady period of growth from 1992, Graham Hazell came on board as our new Managing Director. Graham brought years of sales & strategy experience to Stonegate, facilitating our next period of growth.</div>
                </div>
            </div>
            <div class="column"></div>
            <div class="column"></div>
            <div class="column date">
                <div class="icon">
                    <i class="fa fa-laptop" aria-hidden="true"></i>
                </div>
                <div class="text">
                    <div class="sub">2013</div>
                    <div class="title">Stonegate Online</div>
                    <div class="description">With growth firmly in mind, we launched our online store to cater to a whole new market, and offer value to our existing customers. We were able to reach much further afield and were able to add our value to customers outside the UK.</div>
                </div>
            </div>
            <div class="column date left">
                <div class="icon">
                    <i class="fa fa-globe" aria-hidden="true"></i>
                </div>
                <div class="text">
                    <div class="sub">2013</div>
                    <div class="title">A bigger & better Stonegate</div>
                    <div class="description">Our turnover was growing and through effective supplier partnerships, we were able to extend the range and offer even more products. We needed larger premises to be able to facilitate our next period of growth and so moved to our current home, Melton House.</div>
                </div>
            </div>
            <div class="column"></div>
            <div class="column"></div>
            <div class="column date">
                <div class="icon">
                    <i class="fa fa-university" aria-hidden="true"></i>
                </div>
                <div class="text">
                    <div class="sub">2014</div>
                    <div class="title">Stonegate becomes LTD.</div>
                    <div class="description">After several years of focused, profitable trading we decided to position the business for its next stage of significant growth and in 2014 we moved to the current limited company, Stonegate Precision Tooling Ltd. There’s wasn’t any change to the team or management but was done to ensure we laid the foundations of our market-leading brand.</div>
                </div>
            </div>
            <div class="column date left">
                <div class="icon">
                    <i class="fa fa-eye" aria-hidden="true"></i>
                </div>
                <div class="text">
                    <div class="sub">2016</div>
                    <div class="title">The Stonegate vision takes shape</div>
                    <div class="description">Through extensive strategy work, we knew what we needed to do in order to continue to add value to our customers and 2016 saw us commission research into fully understanding our customers. It was this research that was to shape Stonegate for the future.</div>
                </div>
            </div>
            <div class="column"></div>
            <div class="column"></div>
            <div class="column date">
                <div class="icon">
                    <img src="<?php echo $this->getViewFileUrl('images/about/logo-icon.png'); ?>" class="logo-icon" />
                </div>
                <div class="text">
                    <div class="sub">2017</div>
                    <div class="title">A bold new look</div>
                    <div class="description">Through extensive strategy work, we knew what we needed to do in order to continue to add value to our customers and 2016 saw us commission research into fully understanding our customers. It was this research that was to shape Stonegate for the future.</div>
                </div>
            </div>
            <div class="divider"></div>
        </div>
        <div class="end">
            <div class="title">The Future</div>
            <div class="sub">Bigger & Better!</div>
        </div>
    </div>
</div>