<div class="page-main who-we-are section">
    <h2 class="title">Who we are...</h2>
    <p class="intro">We’ve said it before and we’ll say it again – we are the UK’s most trusted provider of specialist products and knowledge to stone fabricators. Not only this but the leading supplier of specialist products and knowledge to the stone cutting and composite industries. </p></p>
    <div class="column-container colspan-3 total-3">
        <div class="column">
            <img src="<?php echo $this->getViewFileUrl('images/about/intro/customer-service.jpg'); ?>" class="section-image" />
            <p class="description">Stonegate is made up of the hard-working and dedicated team that has ensured our success, we’re a humble bunch but doesn’t mean that we don’t have huge ambitions. We firmly believe that no matter the challenge, we’re better together!</p>
            <a href="<?php echo $this->getUrl('customer-service'); ?>" class="action primary">Customer Service</a>
        </div>
        <div class="column">
            <img src="<?php echo $this->getViewFileUrl('images/about/intro/our-brands.jpg'); ?>" class="section-image" />
            <p class="description">Everyone here at Stonegate works towards our one mission and we have grown our business by providing the very best products, unbeatable service and adding real value to the industry in which we work.</p>
            <a href="<?php echo $this->getUrl('brands'); ?>" class="action primary">Our Brands</a>
        </div>
        <div class="column">
            <img src="<?php echo $this->getViewFileUrl('images/about/intro/our-team.jpg'); ?>" class="section-image" />
            <p class="description">The effort of our incredible team working alongside our valued customers has got us to where we are today and will continue to ensure we thrive and continue to be able to offer our unique value proposition for the benefit of our customers’ business growth.</p>
            <a href="<?php echo $this->getUrl('our-team'); ?>" class="action primary">Who's on the Team?</a>
        </div>
    </div>
</div>