<div class="fullwidth objectives">
    <div class="image-wrapper column">
        <img src="<?php echo $this->getViewFileUrl('images/about/objectives-banner.jpg'); ?>" />
    </div>
    <div class="text-wrapper column">
        <div class="objective mission">
            <div class="text">
                <div class="icon">
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                </div>
                <h4 class="title">Our Mission</h4>
                <p>Stonegate is a team of highly trained solution providers supplying tooling to the stone industries. We will consistently provide our valued customers with quality performance products; select all products from reputable manufacturers and deliver orders to meet agreed delivery deadlines.Our aim is 100% customer satisfaction</p>
            </div>
        </div>
        <div class="objective vision">
            <div class="text">
                <div class="icon">
                    <i class="fa fa-eye" aria-hidden="true"></i>
                </div>
                <h4 class="title">Our Vision</h4>
                <p>Stonegate will remain the market leader in the stone and composite industries in the UK and expand its offering globally. This will be achieved by providing innovative performance products and outstanding customer services, whilst being recognised by its employees as a great place to work.</p>
            </div>
        </div>
        <div class="objective values">
            <div class="text">
                <div class="icon">
                    <i class="fa fa-book" aria-hidden="true"></i>
                </div>
                <h4 class="title">Our Values</h4>
                <p>To provide a return on investment to fund future growth of the company, development and training of our teams and a substantial contribution to a wide range of charitable needs. To exceed in honesty, loyalty and integrity. To work enthusiastically and efficiently, supporting all in a friendly manner and with respect. To have the capacity to initiate and see though to a satisfactory completion any tasks we’re involved in.  in short, to be winners and finishers!</p>
            </div>
        </div>
    </div>
</div>