<div class="fullwidth service-guarantee">
    <div class="page-main section">
        <div class="text">
            <div class="subtitle">Service Guarantee</div>
            <h2 class="title">Our Promise to You...</h2>
            <div class="heading">Being in business is tough enough - Stonegate is here to make your life easier.</div>
            <p>Every product on every shelf carries a 30-day, risk-free guarantee. If you are not entirely satisfield with your purchase, and we mean really satisfield, simply return it for a prompt and courteous refund.</p>
            <p>In the unlikely event we get your order wrong, call us and we’ll fix it. If your order the wrong part, don’t worry - just call our customer service department and we’ll fix it straight away.</p>
            <p>We’ll bring you the latest, proven products and guarantee a 95% order fulfilment on all stock items (we managed 97% on orders troughout 2015). We also offer next day delivery on all stock items ordered before 3pm.</p>
            <p>At Stonegate, we promise to deliver over 98% of orders on time and in full, satisfying our ‘right-first-time’ approach.</p>
        </div>
    </div>
</div>