<?php
$iframe_string = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('experience_stonegate_video_embed')->toHtml();
preg_match('/src="([^"]+)"/', strip_tags($iframe_string, '<iframe>'), $match);
$url = $match[1];
?>

<div class="fullwidth video">
    <div class="page-main">
        <div class="play-video video-action">
            <i class="fa fa-heart" aria-hidden="true"></i>
        </div>
        <div class="title">Passionate about what we do</div>
        <div class="description">Stonegate, the UK’s most trusted provider of specialist products and knowledge to stone fabricators. As a business with a mission built on people and culture, we’re passionate about what we do. Experience for yourself the Stonegate difference.</div>
    </div>
</div>
<div class="red-line"></div>
<!--<div class="dark-overlay video-action close"></div>-->
<!--<div class="video modal-window">-->
<!--    <div class="video-action close"></div>-->
<!--    <div class="embed-container">-->
<!--        <iframe class="video-embed" src="--><?php //echo $url; ?><!--"></iframe>-->
<!--    </div>-->
<!--</div>-->
<!--<script type="text/javascript">-->
<!--    requirejs(['jquery'], function ($) {-->
<!--        $('.video-action').click(function() {-->
<!--            if ($(this).hasClass('play-video')) {-->
<!--                $('.video.modal-window, .dark-overlay').addClass('visible');-->
<!--                $('.modal-window .video-embed')[0].src += '?rel=0&autoplay=1';-->
<!--            } else if ($(this).hasClass('close')) {-->
<!--                $('.video.modal-window, .dark-overlay').removeClass('visible');-->
<!--            }-->
<!--        });-->
<!--    });-->
<!--</script>-->