<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>

<?php
$_postCollection = $block->getPostCollection();
$i = 1;
?>
<?php if ($_postCollection->count()) { ?>
    <div class="widget block block-recent-posts" data-bind="scope: 'recemt-posts'">
        <div class="block-title">
            <strong><?php echo __('Gallery') ?></strong>
        </div>
        <div class="block-content gallery">
            <?php foreach ($_postCollection as $_post) { ?>
                <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                    <a href="<?php echo $_post->getPostUrl() ?>"
                       class="image-container">
                                            <span class="image-wrapper">
                                                <img src="<?php echo $featuredImage ?>"
                                                     class="image"/>
                                            </span>
                    </a>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
<?php } ?>