<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>

<?php
$_postCollection = $block->getPostCollection();
$i = 1;
?>
<?php if ($_postCollection->count()) { ?>
<div class="widget block block-recent-posts" data-bind="scope: 'recemt-posts'">
    <div class="block-title">
        <strong><?php echo __('Recent Posts') ?></strong>
    </div>
    <div class="block-content">
        <?php foreach ($_postCollection as $_post) { ?>
            <div class="item">
                <a class="post-item-link"
                   href="<?php echo $_post->getPostUrl() ?>">
                    <?php echo $_post->getPublishDate('M d, Y') ?>
                </a>
                <p>
                    <?php
                    $string = strip_tags($_post->getContent());

                    if (strlen($string) > 120) {
                        $stringCut = substr($string, 0, 120);
                        $string = substr($stringCut, 0, strrpos($stringCut, ' ')) . ' [<a href="' . $_post->getPostUrl() .'" class="more">more</a>]';
                    }
                    echo $string;
                    ?>
                </p>
            </div>
            <?php
            if (++$i == 3) {
                break;
            }
            ?>
        <?php } ?>
    </div>
</div>
<?php } ?>