<?php

//Get MageQuote and Quote
$mageQuote = $block->getMageQuote();
$quote = $block->getQuote();

//Get Helper Data And Config
$editorHelper = $this->helper('Lof\RequestForQuote\Helper\Wysiwygeditor');
$moduleHelper = $block->getModuleHelper();
$enable_quote_totals = $moduleHelper->getConfig("quote_admin_setting/enable_quote_totals");
$enable_admin_note = $moduleHelper->getConfig("quote_admin_setting/enable_admin_note");
$enable_terms = $moduleHelper->getConfig("quote_admin_setting/enable_terms");
$enable_wtexpect = $moduleHelper->getConfig("quote_admin_setting/enable_wtexpect");
$enable_break_line = $moduleHelper->getConfig("quote_admin_setting/enable_break_line");

//Get Customer
$customer = $mageQuote->getCustomer();
$orderAdminDate = $block->formatDate(
    $block->getOrderAdminDate($mageQuote->getCreatedAt()),
    \IntlDateFormatter::MEDIUM,
    true
);

$firstName = $mageQuote->getData('customer_firstname');
$lastName = $mageQuote->getData('customer_lastname');

if (!$firstName && $quote->getData("first_name")) {
    $firstName = $quote->getData("first_name");
}
if (!$lastName && $quote->getData("last_name")) {
    $lastName = $quote->getData("last_name");
}

$store = $block->getStore($mageQuote->getStoreId());

$shippingAddress = $block->getMageQuoteAddress();
$billingAddress = $block->getMageQuoteBillingAddress();

$quoteData = $block->getQuoteFieldData();
$quoteRemind = $quote->getRemind();
$quoteRemind = ($quoteRemind != '0000-00-00 00:00:00') ? $quoteRemind : '';
$orderStoreDate = $block->formatDate(
    $mageQuote->getCreatedAt(),
    \IntlDateFormatter::MEDIUM,
    true,
    $block->getTimezoneForStore($store)
);

?>
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?php echo __('Quote & Account Information') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <?php /* Quote Information */ ?>
            <div class="admin__page-section-item-title">
                <span class="title">
                    <?php echo __('Quote # %1', $quote->getIncrementId()); ?>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tr>
                        <th><?php echo __('Quote Date') ?></th>
                        <td><?php echo $orderAdminDate ?></td>
                    </tr>
                    <?php if ($orderAdminDate != $orderStoreDate): ?>
                        <tr>
                            <th><?php echo __(
                                    'Quote Date (%1)',
                                    $block->getTimezoneForStore($mageQuote->getStore())
                                ) ?></th>
                            <td><?php echo $orderStoreDate ?></td>
                        </tr>
                    <?php endif; ?>
                    <tr>
                        <th><?php echo __('Quote Status') ?></th>
                        <td>
                                <span id="order_status">
                                    <?php $availableStatuses = $quote->getAvailableStatuses(); ?>
                                    <select name="status" class="select admin__control-select">
                                        <?php foreach ($availableStatuses as $k => $v) { ?>
                                            <option value="<?php echo $k ?>"
                                                    <?php if ($k == $quote->getStatus()) { ?>selected<?php } ?>><?php echo $v ?></option>
                                        <?php } ?>
                                    </select>
                                </span>
                        </td>
                    </tr>

                    <?php if ($block->isSingleStoreMode() == false): ?>
                        <tr>
                            <th><?php echo __('Purchased From') ?></th>
                            <td><?php echo $block->getOrderStoreName() ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($mageQuote->getRelationChildId()): ?>
                        <tr>
                            <th><?php echo __('Link to the New Order') ?></th>
                            <td><a href="<?php echo $block->getViewUrl($mageQuote->getRelationChildId()) ?>">
                                    <?php echo $mageQuote->getRelationChildRealId() ?>
                                </a></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($mageQuote->getRelationParentId()): ?>
                        <tr>
                            <th><?php echo __('Link to the Previous Order') ?></th>
                            <td><a href="<?php echo $block->getViewUrl($mageQuote->getRelationParentId()) ?>">
                                    <?php echo $mageQuote->getRelationParentRealId() ?>
                                </a></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($mageQuote->getRemoteIp()): ?>
                        <tr>
                            <th><?php echo __('Placed from IP') ?></th>
                            <td><?php echo $mageQuote->getRemoteIp();
                                echo ($mageQuote->getXForwardedFor()) ? ' (' . $block->escapeHtml($mageQuote->getXForwardedFor()) . ')' : ''; ?></td>
                        </tr>
                    <?php endif; ?>
                    <tr>
                        <th><?php echo __('Expiry Date') ?></th>
                        <td>
                                <span class="quote-expiry-date">
                                <input id="quote-expiry" type="text" name="expiry"
                                       class="input-text admin__control-text"
                                       value="<?php echo $quote->getExpiry() ? $block->formatTheDate($quote->getExpiry(), "Y-m-d") : '' ?>"/>
                                </span>
                            <div class="admin__actions-switch" data-role="switcher">
                                <input id="quote-expiry-switch"
                                       name="send_expiry_email"
                                       type="checkbox"
                                       class="admin__actions-switch-checkbox"
                                       value="<?php echo (int)$quote->getSendExpiryEmail(); ?>" <?php echo $quote->getSendExpiryEmail() ? "checked" : ""; ?>/>
                                <label class="admin__actions-switch-label"
                                       for="quote-expiry-switch">
                                        <span class="admin__actions-switch-text"
                                              data-text-on="<?php echo __("Yes"); ?>"
                                              data-text-off="<?php echo __("No"); ?>"></span>
                                </label>
                                <div class="switcher-caption"><?php echo __("[send expiry email]"); ?></div>
                            </div>
                            <script>
                                require([
                                    "jquery",
                                    "mage/calendar"
                                ], function ($) {
                                    $("#quote-expiry").calendar({
                                        dateFormat: "<?php echo $block->getDateFormat() ?>",
                                        buttonText: "<?php echo __('Select Date') ?>"
                                    });
                                });
                            </script>

                        </td>
                    </tr>
                    <tr>
                        <th><?php echo __('Reminder Date') ?></th>
                        <td>
                                <span class="quote-remind-date">
                                <input id="quote-remind" type="text" name="remind"
                                       class="input-text admin__control-text"
                                       value="<?php echo $quote->getRemind() ? $block->formatTheDate($quote->getRemind(), "Y-m-d") : '' ?>"/>
                                </span>
                            <div class="admin__actions-switch" data-role="switcher">
                                <input id="quote-reminder-switch"
                                       name="send_remind_email"
                                       type="checkbox"
                                       class="admin__actions-switch-checkbox"
                                       value="<?php echo (int)$quote->getSendRemindEmail(); ?>" <?php echo $quote->getSendRemindEmail() ? "checked" : ""; ?>/>
                                <label class="admin__actions-switch-label"
                                       for="quote-reminder-switch">
                                        <span class="admin__actions-switch-text"
                                              data-text-on="<?php echo __("Yes"); ?>"
                                              data-text-off="<?php echo __("No"); ?>"></span>
                                </label>
                                <div class="switcher-caption"><?php echo __("[send reminder email]"); ?></div>
                            </div>
                            <script>
                                require([
                                    "jquery",
                                    "mage/calendar"
                                ], function ($) {
                                    $("#quote-remind").calendar({
                                        dateFormat: "<?php echo $block->getDateFormat() ?>",
                                        buttonText: "<?php echo __('Select Date') ?>"
                                    });
                                });
                            </script>

                        </td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <?php /* Account Information */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo __('Account Information') ?></span>
                <div class="actions"><?php echo $block->getAccountEditLink() ?></div>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tr>
                        <th><?php echo __('Customer Name') ?></th>
                        <td>
                            <?php if ($_customerUrl = $block->getCustomerViewUrl()) : ?>
                                <a href="<?php echo $_customerUrl ?>" target="_blank">
                                    <span><?php echo $block->escapeHtml($firstName . ' ' . $lastName) ?></span>
                                </a>
                            <?php else: ?>
                                <?php echo $block->escapeHtml($firstName . ' ' . $lastName) ?>
                            <?php endif; ?>
                            <input type="hidden" name="mage_quote[customer_firstname]"
                                   value="<?php echo $firstName; ?>"/>
                            <input type="hidden" name="mage_quote[customer_lastname]"
                                   value="<?php echo $lastName; ?>"/>
                        </td>
                    </tr>
                    <?php if (isset($quoteData['email']) && $quoteData['email']) { ?>
                        <tr>
                            <th><?php echo __('Email') ?></th>
                            <td>
                                <a href="mailto:<?php echo $block->escapeHtml($quoteData['email']) ?>"><?php echo $block->escapeHtml($quoteData['email']) ?></a>
                            </td>
                        </tr>
                    <?php } elseif ($mageQuote->getCustomerEmail()) { ?>
                        <tr>
                            <th><?php echo __('Email') ?></th>
                            <td>
                                <a href="mailto:<?php echo $block->escapeHtml($mageQuote->getCustomerEmail()) ?>"><?php echo $block->escapeHtml($mageQuote->getCustomerEmail()) ?></a>
                            </td>
                        </tr>
                    <?php } ?>
                    <?php if ($_groupName = $block->getCustomerGroupName()) : ?>
                        <tr>
                            <th><?php echo __('Customer Group') ?></th>
                            <td><?php echo $_groupName ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (isset($quoteData['company']) && $quoteData['company']) : ?>
                        <tr>
                            <th><?php echo __('Company') ?></th>
                            <td><?php echo $quoteData['company'] ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (isset($quoteData['telephone']) && $quoteData['telephone']) : ?>
                        <tr>
                            <th><?php echo __('Telephone') ?></th>
                            <td><?php echo $quoteData['telephone'] ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (isset($quoteData['address']) && $quoteData['address']) : ?>
                        <tr>
                            <th><?php echo __('Address') ?></th>
                            <td><?php echo $quoteData['address'] ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if (isset($quoteData['tax_id']) && $quoteData['tax_id']) : ?>
                        <tr>
                            <th><?php echo __('Tax Code') ?></th>
                            <td><?php echo $quoteData['tax_id'] ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php foreach ($block->getCustomerAccountData() as $data): ?>
                        <tr>
                            <th><?php echo $data['label'] ?></th>
                            <td><?php echo $data['value'] ?></td>
                        </tr>
                    <?php endforeach; ?>
                    <?php if ($questions = $block->getQuestions()) : ?>
                        <?php foreach ($questions as $question): ?>
                            <tr>
                                <th><?php echo $question['label']; ?></th>
                                <td><?php echo $question['value'] ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </table>
            </div>
        </div>
    </div>
</section>