<?php /** @var $block \Magento\Catalog\Block\Product\Image */
$dataHelper = $this->helper('Magezon\LazyLoad\Helper\Data');
$lazyClasses = $dataHelper->getLazyClasses();
$placeHolderUrl = $dataHelper->getPlaceHolderUrl();
$customAttributes = $block->getCustomAttributes();
if ($placeHolderUrl != $dataHelper->getDefaultPlaceHolderUrl()) {
    $lazyClasses = str_replace('lazy-blur', '', $lazyClasses);
}
if (is_array($customAttributes)) {
    $customAttributes = null;
}
?>

<span class="product-image-container"
      style="width:<?= /* @escapeNotVerified */ $block->getWidth() ?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?= /* @escapeNotVerified */ ($block->getRatio() * 100) ?>%;">
        <img class="product-image-photo <?= $lazyClasses ?>"
            <?= /* @escapeNotVerified */ $customAttributes ?>
                src="<?= $placeHolderUrl ?>"
            data-src="<?= /* @escapeNotVerified */ $block->getImageUrl() ?>"
            width="<?= /* @escapeNotVerified */ $block->getResizedImageWidth() ?>"
            height="<?= /* @escapeNotVerified */ $block->getResizedImageHeight() ?>"
            alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true) ?>"/></span>
</span>
