<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base"><?php /* @escapeNotVerified */ echo __('Our Brands') ?></span>
    </h1>
</div>
<div class="brands-grid">
    <div class="brand">
        <div class="logo-container">
            <span class="logo-wrapper">
                <img src="<?php echo $this->getViewFileUrl('images/brand-logo.png'); ?>" class="logo" />
            </span>
        </div>
        <div class="info">
            <div class="wrapper">
                <div class="name">Aztec</div>
                <div class="description">
                    <p>Lorem ipsum dolor sit amet, solum eruditi ut mel, rebum nemore iisque sit id, prima imperdiet elaboraret mea an. Vel ea ipsum neglegentur. Per tota legimus inimicus id, ex sed ipsum imperdiet. Similique voluptatum mel ea, est in error zril. Movet docendi omnesque duo ut, cu stet inani vis.</p>
                    <p>Cum et aeterno insolens, at modus assum eligendi sea. Prima virtute consulatu eum ei, his no aperiri mediocrem similique. Te iuvaret accumsan vis. Affert ubique mea cu. Id vix primis animal, eu pri laudem placerat. Pri diam senserit eu, justo gubergren sea ut.</p>
                </div>
                <a href="<?php echo $this->getUrl(); ?>" class="action primary">Shop Now</a>
            </div>
        </div>
    </div>
</div>