<div class="faq-container">
    <div class="faq">
        <div class="question">
            <h5>What We Collect</h5>
        </div>
        <div class="answer">
            <p>We may collect the following information:</p>
            <ul>
                <li>Your name</li>
                <li>Your contact information including email address</li>
                <li>Demographic information about you such as postcode, preferences and interests</li>
                <li>Other information relevant to customer surveys and/or offers</li>
            </ul>
            <p>For the exhaustive list of cookies we collect see the List of cookies we collect section.</p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>What we do with the information we gather</h5>
        </div>
        <div class="answer">
            <p>We require this information to understand your needs and provide you with a better service, and in particular for the following reasons:</p>
            <p>Internal record keeping.</p>
            <p>We may use the information to improve our products and services.</p>
            <p>We may periodically send promotional emails about new products, special offers or other information which we think you may find interesting using the email address which you have provided.</p>
            <p>From time to time, we may also use your information to contact you for market research purposes. We may contact you by email, phone, fax or mail. We may use the information to customise the website according to your interests.</p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>Security</h5>
        </div>
        <div class="answer">
            <p>We are committed to ensuring that your information is secure. In order to prevent unauthorised access or disclosure, we have put in place suitable physical, electronic and managerial procedures to safeguard and secure the information we collect online.</p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>How we use Cookies</h5>
        </div>
        <div class="answer">
            <p>A cookie is a small file which asks permission to be placed on your computer's hard drive. Once you agree, the file is added and the cookie helps analyse web traffic or lets you know when you visit a particular site. Cookies allow web applications to respond to you as an individual. The web application can tailor its operations to your needs, likes and dislikes by gathering and remembering information about your preferences.</p>
            <p>We use traffic log cookies to identify which pages are being used. This helps us analyse data about web page traffic and improve our website in order to tailor it to customer needs. We only use this information for statistical analysis purposes and then the data is removed from the system.</p>
            <p>Overall, cookies help us provide you with a better website, by enabling us to monitor which pages you find useful and which you do not. A cookie in no way gives us access to your computer or any information about you, other than the data you choose to share with us. You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. This may prevent you from taking full advantage of the website.</p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>Controlling your personal information</h5>
        </div>
        <div class="answer">
            <p>You may choose to restrict the collection or use of your personal information in the following ways:</p>
            <p>whenever you are asked to fill in a form on the website, look for the box that you can click to indicate that you do not want the information to be used by anybody for direct marketing purposes</p>
            <p>if you have previously agreed to us using your personal information for direct marketing purposes, you may change your mind at any time by writing to or emailing us at info@stonegatetooling.co.uk</p>
            <p>We will not sell, distribute or lease your personal information to third parties unless we have your permission or are required by law to do so. We may use your personal information to send you promotional information about third parties which we think you may find interesting if you tell us that you wish this to happen.</p>
            <p>You may request details of personal information which we hold about you under the Data Protection Act 1998. A small fee will be payable. If you would like a copy of the information held on you please write to Melton House Wyke Way Melton East Yorkshire HU14 3HJ.</p>
            <p>If you believe that any information we are holding on you is incorrect or incomplete, please write to or email us as soon as possible, at the above address. We will promptly correct any information found to be incorrect.</p>
        </div>
    </div>
</div>
<script type="text/javascript">
    requirejs(['jquery'], function($) {
        $('.faq-container .faq').click(function() {
            if (!$(this).hasClass('active')) {
                $('.faq .answer').stop().slideUp(150);
                $('.faq').removeClass('active');
                $(this).addClass('active').find('.answer').stop().slideDown(150);
            }
        });
    });
</script>
<h3 class="title">List of Cookies We Collect</h3>
<p>The table below lists the cookies we collect and what information they store.</p>
<table class="cookie-table">
    <thead>
    <tr>
        <th>Cookie Name</th>
        <th>Cookie description</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Cart</td>
        <td>The association with your shopping cart.</td>
    </tr>
    <tr>
        <td>Category_Info</td>
        <td>Stores the category info on the page, that allows to display pages more quickly.</td>
    </tr>
    <tr>
        <td>Compare</td>
        <td>The items that you have in the Compare Products list.</td>
    </tr>
    <tr>
        <td>Currency</td>
        <td>Your preferred currency</td>
    </tr>
    <tr>
        <td>Customer</td>
        <td>An encrypted version of your customer id with the store.</td>
    </tr>
    <tr>
        <td>Customer_Auth</td>
        <td>An indicator if you are currently logged into the store.</td>
    </tr>
    <tr>
        <td>Customer_Info</td>
        <td>An encrypted version of the customer group you belong to.</td>
    </tr>
    <tr>
        <td>Customer_Segment_IDs</td>
        <td>Stores the Customer Segment ID</td>
    </tr>
    <tr>
        <td>External_No_Cache</td>
        <td>A flag, which indicates whether caching is disabled or not.</td>
    </tr>
    <tr>
        <td>Frontend</td>
        <td>Your session ID on the server.</td>
    </tr>
    <tr>
        <td>Guest_View</td>
        <td>Allows guests to edit their orders.</td>
    </tr>
    <tr>
        <td>Last_Category</td>
        <td>The last category you visited.</td>
    </tr>
    <tr>
        <td>Last_Product</td>
        <td>The most recent product you have viewed.</td>
    </tr>
    <tr>
        <td>New_Message</td>
        <td>Indicates whether a new message been received.</td>
    </tr>
    <tr>
        <td>No_Cache</td>
        <td>Indicates whether it is allowed to use cache.</td>
    </tr>
    <tr>
        <td>Persistent_Shopping_Cart</td>
        <td>A link to information about your cart and viewing history if you have asked the site.</td>
    </tr>
    <tr>
        <td>Poll</td>
        <td>The ID of any polls you have recently voted on our website.</td>
    </tr>
    <tr>
        <td>Polln</td>
        <td>Information on what polls you have voted on our website.</td>
    </tr>
    <tr>
        <td>Recently_Compared</td>
        <td>The items that you have recently compared.</td>
    </tr>
    <tr>
        <td>STF</td>
        <td>Information on products you have emailed to friends.</td>
    </tr>
    <tr>
        <td>Store</td>
        <td>The store view or language you have selected.</td>
    </tr>
    <tr>
        <td>User_Allowed_Save_Cookies</td>
        <td>Indicates whether a customer allowed to use cookies.</td>
    </tr>
    <tr>
        <td>Viewed_Product_Ids</td>
        <td>The products that you have recently viewed.</td>
    </tr>
    <tr>
        <td>Wishlist</td>
        <td>An encrypted list of products added to your Wishlist.</td>
    </tr>
    <tr>
        <td>Wishlist_Cnt</td>
        <td>The number of items in your Wishlist.</td>
    </tr>
    </tbody>
</table>