<div class="map-container">
    <div id="maps" style="width:100%;"></div>
    <script type="text/javascript" src="//maps.google.com/maps/api/js?key=AIzaSyDbqFmtd83DZPPNHAqvae5ncoG9YcaHC3E"></script>
    <script type="text/javascript">
        var stonegateLatLng = new google.maps.LatLng(53.7216738, -0.5355129);

        var map = new google.maps.Map(document.getElementById("maps"), {
            zoom: 10,
            scrollwheel: false,
            center: stonegateLatLng
        });

        var stonegateMarker = new google.maps.Marker({
            map: map,
            position: stonegateLatLng
        });

        var stonegateInfo = new google.maps.InfoWindow({
            content: "<div class='map-overlay'><a href=\"https://www.google.co.uk/maps/dir//Melton%20House,%20HU14%203HJ\">Stonegate Tooling<br />Directions</a> <i class='fa fa-chevron-circle-right' aria-hidden='true'></i></div>"
        });

        google.maps.event.addListener(stonegateMarker, "click", function () {
            stonegateInfo.open(map, stonegateMarker);
        });

        stonegateInfo.open(map, stonegateMarker);
    </script>
</div>