<div class="fullwidth trade-features">
    <div class="page-main section">
        <div class="container">
            <div class="image-wrapper">
                <img src="<?php echo $this->getViewFileUrl('images/about/trade-feature-tablet.png'); ?>" class="tablet"/>
                <img src="<?php echo $this->getViewFileUrl('images/about/trade-feature-tablet-shadow.png'); ?>" class="shadow"/>
            </div>
            <div class="features-wrapper">
                <h2 class="title">Stonegate Trade Account</h2>
                <div class="features column-container colspan-2">
                    <div class="column feature">
                        <div class="title-wrapper">
                            <div class="icon">
                                <i class="fa fa-clock-o" aria-hidden="true"></i>
                            </div>
                            <div class="title">Access your account 24/7</div>
                        </div>
                        <div class="description">An online account means you benefit from being able to access and manage
                            your account, terms and trade online for next day delivery where available, anytime, anywhere.
                        </div>
                    </div>
                    <div class="column feature">
                        <div class="title-wrapper">
                            <div class="icon">
                                <i class="fa fa-calendar" aria-hidden="true"></i>
                            </div>
                            <div class="title">30 day credit</div>
                        </div>
                        <div class="description">Trade Account customers benefit from 30-day credit with us here at
                            Stonegate, giving your business the flexibility it needs to stay operational and efficient.
                        </div>
                    </div>
                    <div class="column feature">
                        <div class="title-wrapper">
                            <div class="icon">
                                <i class="fa fa-user" aria-hidden="true"></i>
                            </div>
                            <div class="title">Dedicated support & backup</div>
                        </div>
                        <div class="description">Online customers benefit from the same market-leading service offered by
                            Stonegate and we are here to advise on the best tools for your job, feeds and speeds and
                            technical advice.
                        </div>
                    </div>
                    <div class="column feature">
                        <div class="title-wrapper">
                            <div class="icon">
                                <i class="fa fa-users" aria-hidden="true"></i>
                            </div>
                            <div class="title">Multiple account users</div>
                        </div>
                        <div class="description">Fully managed online, customers benefit from being able to manage users,
                            spending limits, addresses and invoices all in comfort and with ease. You’re in control of who
                            purchases tooling.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>