<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<li class="post-holder post-holder-<?php echo $_post->getId() ?>">
    <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
        <div class="post-ftimg-hld">
            <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>" class="image-container">
                <span class="image-wrapper">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" class="image"/>
                </span>
            </a>
        </div>
    <?php } ?>
    <div class="post-header">
        <div class="post-title-holder clearfix">
            <h2 class="post-title">
                <a class="post-item-link"
                   href="<?php echo $_postUrl ?>">
                    <?php echo $_postName; ?>
                </a>
            </h2>
        </div>
        <?php echo $this->getInfoHtml() ?>
    </div>

    <div class="post-content">
        <div class="post-description clearfix">
            <div class="post-text-hld clearfix">
                <?php
                $string = strip_tags($block->getShorContent());

                if (strlen($string) > 500) {
                    $stringCut = substr($string, 0, 500);
                    $string = substr($stringCut, 0, strrpos($stringCut, ' ')) . ' [...]';
                }
                echo $string;
                ?>
            </div>
            <a class="action primary" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>"
               >
               <?php echo __('Read more') ?>
            </a>
        </div>
    </div>
    <div class="post-footer">

    </div>
</li>