<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <?php if($_product->getTypeId() == 'grouped'): ?>
        <a href="<?php echo $block->getUrl('compare/add/index'); ?>" class="action tocompare grouped" disabled="true">Compare Selected</a>
        <div class="totals">
            <span class="title">Total</span>
            <span class="subtotal">£0.00</span>
        </div>
    <?php endif; ?>
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
            <div class="qty-wrapper">
                <div class="field qty">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty:') ?></span></label>
                    <div class="control">
                        <div class="qty-input">
                            <input type="number"
                                   name="qty"
                                   id="qty"
                                   maxlength="12"
                                   value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                                   title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                                   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                            />
                            <div class="add"></div>
                            <div class="subtract"></div>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                requirejs(['jquery'], function($) {
                    $('body').on('click', '.qty-wrapper .qty-input > div', function () {
                        var control = $(this);
                        var input = control.siblings('input');
                        input.focus();
                        var value = parseInt(input.val());

                        if (control.hasClass('subtract')) {
                            input.val(value - 1).change();
                        }

                        if (control.hasClass('add')) {
                            input.val(value + 1).change();
                        }

                        if (input.val() < 0) {
                            input.val(0).change();
                        }

                        input.change();
                    });
                });
            </script>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
        <?php if ($block->shouldRenderQuantity()): ?>
            <?php echo $this->getLayout()
                ->createBlock('Magento\Catalog\Block\Product\View\AddTo\Compare')
                ->setTemplate('Magento_Catalog::product/view/addto/compare.phtml')
                ->toHtml(); ?>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>