<?php
$_product = $block->getProduct();
?>

<?php if ($_product->getIsSalable()): ?>
    <?php
    $time = '4pm';
    if(date('D') == 'Fri') :
        $time = '3pm';
    endif;
    ?>
    <div class="stock available"><span>Availability: </span><span class="availability"><?php /* @escapeNotVerified */ echo __('In stock. Order by %1 for next day delivery.', $time) ?></span></div>
<?php else: ?>
    <div class="stock unavailable"><span>Availability: </span><span class="availability"><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
<?php endif; ?>