<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * New Customer block template
 *
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <div class="block block-new-customer">
        <div class="block-title">
            <strong id="block-new-customer-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('New Customers') ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-new-customer-heading">
            <div class="subtitle"><?php /* @escapeNotVerified */ echo __('Register with us now for added benefits!') ?></div>
            <div class="description">
                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('register_account_description')->toHtml(); ?>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <a href="<?php /* @escapeNotVerified */ echo $block->getCreateAccountUrl() ?>" class="action create primary"><span><?php /* @escapeNotVerified */ echo __('Register') ?></span></a>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
