<div class="page-title-wrapper">
    <h1 class="page-title"><span class="base">Website Terms &amp; Condtions of Sale</span></h1>
</div>
<p><strong class="highlight">STONEGATE PRECISION TOOLING LTD WEBSITE TERMS AND CONDITIONS OF SALE</strong></p>
<p>These terms and conditions of sale tell you information about STONEGATE PRECISION TOOLING LTD (Registered in England
    &amp; Wales No. 07876144) whose principal office is at Melton House, Wyke Way, Melton, East Yorkshire, HU14 3HJ
    ("We", "we" or "us") and the legal terms and conditions ("Terms") on which we sell any of the products ("Products")
    listed on our website www.stonegatetooling.com ("our site"), in our catalogues, other publications or otherwise to
    you and where such sale takes place through our site.</p>
<p>These Terms will apply to any contract between us for the sale of Products to you where such sale takes place through
    our site ("Contract"). Please read these Terms carefully and make sure that you understand them, before ordering or
    purchasing any Products from us. Please note that by ordering or purchasing any of our Products, you agree to be
    bound by these Terms and any other documents expressly referred to in them.</p>
<p>You should print or keep a copy of these Terms for future reference.</p>
<p>We amend these Terms from time to time as set out in clause 6.</p>
<p>Every time you wish to order or purchase Products, please check these Terms to ensure you understand the terms which
    will apply at that time. These Terms, and any Contract between us, are only in the English language.</p>
<div class="term">
    <h4 class="title">1. Contacting Us</h4>
    <p>To contact us, please write to STONEGATE PRECISION TOOLING LTD at Melton House, Wyke Way, Melton, East Yorkshire, HU14 3HJ.</p>
</div>
<div class="term">
    <h4 class="title">2. Our Products</h4>
    <p>To contact us, please write to STONEGATE PRECISION TOOLING LTD at Melton House, Wyke Way, Melton, East Yorkshire, HU14 3HJ.</p>
    <ul class="terms-list">
        <li><b>2.1</b>The images and descriptions of the Products on our site and in our catalogue or other publications ("our publications") are for illustrative purposes only. Although we have made every effort to display the colours accurately, we cannot guarantee that the colours accurately reflect the colour of the Products. Your Products may vary slightly from those images or descriptions.</li>
        <li><b>2.2</b>The packaging of the Products may vary from that shown on images or descriptions in our publications.</li>
        <li><b>2.3</b>All Products shown in our publications and on our site are subject to availability. We will inform you as soon as possible if the Product you have ordered or purchased is not available and we will not process your order or purchase if made.</li>
    </ul>
</div>
<div class="term">
    <h4 class="title">3. If you are a consumer</h4>
    <p>This clause 3 only applies if you are a consumer.</p>
    <p>As a consumer, you have legal rights in relation to Products that are faulty or not as described. Advice about your legal rights is available from your local Citizens' Advice Bureau or Trading Standards office. Nothing in these Terms will affect these legal rights.</p>
</div>
<div class="term">
    <h4 class="title">4. If you are a business customer</h4>
    <p>This clause 4 only applies if you are a business.</p>
    <ul class="terms-list">
        <li><b>4.1</b>If you are not a consumer, you confirm that you have authority to bind any business on whose behalf you agree to purchase Products.</li>
        <li><b>4.2</b>These Terms and any document expressly referred to in them constitute the entire agreement between you and us. You acknowledge that you have </li>
    </ul>
</div>
<div class="term">
    <h4 class="title">5. How the contract is formed between you and us</h4>
    <ul class="terms-list">
        <li><b>5.1</b>For the steps you need to take to place an order on our site, please follow the guidance set out on our site.</li>
        <li><b>5.2</b>After you place an order, you will receive an e-mail from us acknowledging that we have received your order. However, please note that this does not mean that your order has been accepted. Our acceptance of your order will take place as described in clause 5.3.</li>
        <li><b>5.3</b>We will confirm our acceptance to you by sending you an e-mail that confirms that the Products have been dispatched ("Dispatch Confirmation"). The Contract between us will only be formed when we send you the Dispatch Confirmation.</li>
        <li><b>5.4</b>If we are unable to supply you with a Product, for example because that Product is not in stock or no longer available or because of an error in the price on our site or our publications as referred to in clause 10.5, we will inform you of this by e-mail and we will not process your order. If you have already paid for the Products, we will refund you the full amount as soon as possible.</li>
    </ul>
</div>
<div class="term">
    <h4 class="title">6. Our right to vary these terms</h4>
    <ul class="terms-list">
        <li><b>6.1</b>We may revise these Terms from time to time.</li>
        <li><b>6.2</b>Every time you order Products from us, the Terms in force at that time will apply to the Contract between you and us.</li>
    </ul>
</div>
<div class="term">
    <h4 class="title">7. Your right of return and refund</h4>
    <ul class="terms-list">
        <li><b>7.1</b>In order to make a return, you must follow the procedure set out on the Shipping and Returns section of our site https://www.stonegatetooling.com.</li>
        <li><b>7.2</b>If you are a consumer, and have purchased your Products from our site, you have a legal right to cancel a Contract under the Consumer Protection (Distance Selling) Regulations 2000) during the period set out below in clause 7.4. This means that during the relevant period if you change your mind or for any other reason you decide you do not want to keep a Product, you can notify us of your decision to cancel the Contract and receive a refund. Advice about your legal right to cancel the Contract under these regulations is available from your local Citizens' Advice Bureau or Trading Standards office.</li>
        <li>
            <b>7.3</b>
            <p>However, this cancellation right does not apply in the case of:</p>
            <ul class="sub-list">
                <li>(a) any made-to-measure or custom-made products or products made to your specification or clearly personalised;</li>
                <li>(b) newspapers, periodicals or magazines;</li>
                <li>(c) perishable goods and manuals which have been opened and specially constructed items;</li>
                <li>(d) goods that consist of certain hazardous substances; and</li>
                <li>(e) any static-sensitive goods supplied in sealed packaging if the blister or 'peel' packs in which they are supplied have been opened, tampered with or damaged.</li>
            </ul>
        </li>
        <li><b>7.4</b>Your legal right to cancel a Contract starts from the date of the Dispatch Confirmation, which is when the Contract between us is formed. If the Products have already been delivered to you, you have a period of 7 (seven) working days in which you may cancel, starting from the day after the day you receive the Products. Working days means that Saturdays, Sundays or public holidays are not included in this period.</li>
        <li><b>7.5</b>You will receive a full refund of the price you paid for the Products and any applicable delivery charges you paid for. We will process the refund due to you as soon as possible and, in any case, within 30 calendar days of the day on which you gave us notice of cancellation. If you returned the Products to us because they were faulty or mis-described, please see clause 7.6.</li>
        <li><b>7.6</b>If you have returned the Products to us under this clause 7 because they are faulty or mis-described, we will refund the price of a defective Product in full, any applicable delivery charges, and any reasonable costs you incur in returning the item to us.</li>
        <li><b>7.7</b>If applicable, we will refund you on the credit card or debit card used by you to pay.</li>
        <li>
            <b>7.8</b>
            <p>If the Products were delivered to you:</p>
            <ul class="sub-list">
                <li>(a) you must return the Products to us as soon as reasonably practicable. If the Products require collection, we will collect the Products from the address to which they were delivered. We will contact you to arrange a suitable time for collection;</li>
                <li>(b) unless the Products are faulty or not as described (in this case, see clause 7.6), you will be responsible for the cost of returning the Products to us or, where relevant, the cost of us collecting the Products from you;</li>
                <li>(c) you have a legal obligation to keep the Products in your possession and to take reasonable care of the Products while they are in your possession.</li>
            </ul>
        </li>
        <li>
            <b>7.9</b>
            <p>Without prejudice to clauses 7.1 to 7.8 or your statutory rights:</p>
            <ul class="sub-list">
                <li>(a) any Products returned which are not identical in composition, size, colour, specification and finish as those in our catalogue or on our site and have been obtained by us at your request will only be refunded at our absolute discretion;</li>
                <li>(b) where an order has been cancelled within 28 days of receiving the Products, we will examine the returned Products within a reasonable time. Where Products are found to be defective, the price of the Products will be refunded in full; where Products returned in accordance with this clause 7.9(b) are found not to be defective, we reserve the discretion to decide whether to accept the return and to deduct a re-stocking charge of 30% of the price of the Products from any refund to you.</li>
            </ul>
        </li>
        <li><b>7.10</b>All Products must be returned unused, in their original packaging and in a resaleable condition (to be determined in our absolute discretion) and (subject to clauses 7.1 to 7.8) you will be responsible for the costs of returning the Products to us. Subject to clauses 7.1 to 7.8, costs of delivery to you (if any) will not be refunded.</li>
        <li><b>7.11</b>In case of inconsistency, the provisions of this clause 7 shall override any other provisions dealing with Product returns set out on our site.</li>
    </ul>
</div>
<div class="term">
    <h4 class="title">8. Delivery</h4>
    <ul class="terms-list">
        <li><b>8.1</b>Your order will be fulfilled by the estimated delivery date set out in the Dispatch Confirmation, unless there is an Event Outside Our Control. If we 5 are unable to meet the estimated delivery date because of an Event Outside Our Control, we will contact you with a revised estimated delivery date.</li>
        <li><b>8.2</b>Delivery will be completed when we deliver the Products to the address you gave us.</li>
        <li><b>8.3</b>If no one is available at your address to take delivery, we will leave you a note that the Products have been returned to our premises, in which case, please contact us to rearrange delivery. Additional delivery charges may be levied by us in respect of any such rearranged delivery.</li>
        <li><b>8.4</b>The Products will be your responsibility from the completion of delivery.</li>
        <li><b>8.5</b>You own the Products once we have received payment in full, including all applicable delivery charges.</li>
    </ul>
</div>
<div class="term">
    <h4 class="title">9. International delivery</h4>
    <ul class="terms-list">
        <li><b>9.1</b>If you order Products from our site for delivery outside of the UK, your delivery charges will be separately agreed with you and your order may be subject to import duties and taxes which are applied when the delivery reaches that destination. Please note that we have no control over these charges and we cannot predict their amount.</li>
        <li><b>9.2</b>You will be responsible for payment of any such import duties and taxes. Please contact your local customs office for further information before placing your order.</li>
        <li><b>9.3</b>You must comply with all applicable laws and regulations of the country for which the Products are destined. We will not be liable or responsible if you break any such law.</li>
    </ul>
</div>
<div class="term">
    <h4 class="title">10. Price of products and delivery charges</h4>
    <ul class="terms-list">
        <li><b>10.1</b>The prices of the Products will be as quoted on our site or in our publications from time to time. We use our best efforts to ensure that the prices of Products are correct at the time when the relevant information was published. However if we discover an error in the price of Product(s) you ordered, please see clause 10.5 for what happens in this event.</li>
        <li><b>10.2</b>Prices for our Products may change from time to time, but changes will not affect any order which we have confirmed with a Dispatch Confirmation.</li>
        <li><b>10.3</b>Unless otherwise stated, the price of a Product excludes VAT (where applicable) at the applicable current rate chargeable in the UK for the time being. However, if the rate of VAT changes between the date of your order and the date of delivery, we will adjust the VAT you pay, unless you have already paid for the Products in full before the change in VAT takes effect.</li>
        <li><b>10.4</b>Unless otherwise stated or agreed, the price of a Product excludes delivery charges.</li>
        <li><b>10.5</b>Our site and our publications contain a large number of Products. It is always possible that, despite our reasonable efforts, some of the Products on our site or in our publications may be incorrectly priced. If we discover an error in the price of the Products you have ordered we will inform you of this error and we will give you the option of continuing to purchase the Product at the correct price or cancelling your order. We will not process your order until we have your instructions. If we are unable to contact you using the contact details you provided during the order process, we will treat the order as cancelled and notify you. Please note that we do not have to provide the Products to you at the incorrect (lower) price.</li>
    </ul>
</div>
<div class="term">
    <h4 class="title">11. How to pay</h4>
    <ul class="terms-list">
        <li><b>11.1</b>If purchasing Products on our site, please follow the payment instructions provided.</li>
        <li><b>11.2</b>Payment for the Products and all applicable delivery charges is in advance and Products will only be despatched once payment has been received in full.</li>
    </ul>
</div>
<div class="term">
    <h4 class="title">12. Manufacturer guarantees</h4>
    <ul class="terms-list">
        <li><b>12.1</b>Some of the Products we sell to you come with a manufacturer's guarantee. For details of the applicable terms and conditions, please refer to the manufacturer's guarantee provided with the Products.</li>
        <li><b>12.2</b>If you are a consumer, a manufacturer's guarantee is in addition to your legal rights in relation to Products that are faulty or not as described. </li>
    </ul>
</div>
<div class="term">
    <h4 class="title">13. Our liability if you are a business This clause 13 only applies if you are a business customer.</h4>
    <ul class="terms-list">
        <li>
            <b>13.1</b>
            <p>Nothing in these Terms limit or exclude our liability for:</p>
            <ul class="sub-list">
                <li>(a) death or personal injury caused by our negligence;</li>
                <li>(b) fraud or fraudulent misrepresentation;</li>
                <li>(c) breach of the terms implied by section 12 of the Sale of Goods Act 1979 (title and quiet possession); or</li>
                <li>(d) defective products under the Consumer Protection Act 1987.</li>
            </ul>
        </li>
        <li>
            <b>13.2</b>
            <p>Subject to clause 13.1, we will under no circumstances whatever be liable to you, whether in contract, tort (including negligence), breach of statutory duty, or otherwise, arising under or in connection with the Contract for:</p>
            <ul class="sub-list">
                <li>(a) any loss of profits, sales, business, or revenue;</li>
                <li>(b) loss or corruption of data, information or software;</li>
                <li>(c) loss of business opportunity;</li>
                <li>(d) loss of anticipated savings;</li>
                <li>(e) loss of goodwill; or</li>
                <li>(f) any indirect or consequential loss.</li>
            </ul>
        </li>
        <li><b>13.3</b>Subject to clause 13.1 and clause 13.2, our total liability to you in respect of all other losses arising under or in connection with the Contract, whether in contract, tort (including negligence), breach of statutory duty, or otherwise, shall in no circumstances exceed the greater of £50,000 or 200% of the price of the Products.</li>
        <li><b>13.4</b>Except as expressly stated in these Terms, we do not give any representation, warranties or undertakings in relation to the Products. Any representation, condition or warranty which might be implied or incorporated into these Terms by statute, common law or otherwise is excluded to the fullest extent permitted by law. In particular, we will not be responsible for ensuring that the Products are suitable for your purposes.</li>
    </ul>
</div>
<div class="term">
    <h4 class="title">14. Our liability if you are a consumer</h4>
    <p>This clause 14 only applies if you are a consumer.</p>
    <ul class="terms-list">
        <li><b>14.1</b>If we fail to comply with these Terms, we are responsible for loss or damage you suffer that is a foreseeable result of our breach of these Terms or our negligence, but we are not responsible for any loss or damage that is not foreseeable. Loss or damage is foreseeable if they were an obvious consequence of our breach or if they were contemplated by you and us at the time we entered into the Contract.</li>
        <li><b>14.2</b>We only supply the Products for domestic and private use. You agree not to use the product for any commercial, business or re-sale purposes, and we have no liability to you for any loss of profit, loss of business, business interruption, or loss of business opportunity.</li>
        <li>
            <b>14.3</b>
            <p>We do not in any way exclude or limit our liability for:</p>
            <ul class="sub-list">
                <li>(a) death or personal injury caused by our negligence;</li>
                <li>(b) fraud or fraudulent misrepresentation;</li>
                <li>(c) any breach of the terms implied by section 12 of the Sale of Goods Act 1979 (title and quiet possession);</li>
                <li>(d) any breach of the terms implied by section 13 to 15 of the Sale of Goods Act 1979 (description, satisfactory quality, fitness for purpose and samples); and</li>
                <li>(e) defective products under the Consumer Protection Act 1987.</li>
            </ul>
        </li>
        <li><b>14.4</b>Subject to clauses 14.1 to 14.3 (inclusive), our total liability to you in respect of all other losses arising under or in connection with the Contract, whether in contract, tort (including negligence), breach of statutory duty, or otherwise, shall in no circumstances exceed the greater of £50,000 or 200% of the price of the Products.</li>
    </ul>
</div>
<div class="term">
    <h4 class="title">15. Events outside our control</h4>
    <ul class="terms-list">
        <li><b>15.1</b>We will not be liable or responsible for any failure to perform, or delay in performance of, any of our obligations under a Contract that is caused by an Event Outside Our Control. An Event Outside Our Control is defined below in clause 15.2.</li>
        <li><b>15.2</b>An Event Outside Our Control means any act or event beyond our reasonable control, including without limitation strikes, lock-outs or other industrial action by third parties, civil commotion, riot, invasion, terrorist attack or threat of terrorist attack, war (whether declared or not) or threat or preparation for war, fire, explosion, storm, flood, earthquake, subsidence, epidemic or other natural disaster, or failure of public or private telecommunications networks or impossibility of the use of railways, shipping, aircraft, motor transport or other means of public or private transport.</li>
        <li>
            <b>15.3</b>
            <p>If an Event Outside Our Control takes place that affects the performance of our obligations under a Contract:</p>
            <ul class="sub-list">
                <li>(a) we will contact you as soon as reasonably possible to notify you; and</li>
                <li>(b) our obligations under a Contract will be suspended and the time for performance of our obligations will be extended for the duration of the Event Outside Our Control. Where the Event Outside Our Control affects our delivery of Products to you, we will arrange a new delivery date with you after the Event Outside Our Control is over.</li>
            </ul>
        </li>
    </ul>
</div>
<div class="term">
    <h4 class="title">16. Communications between us</h4>
    <ul class="terms-list">
        <li><b>16.1</b>When we refer, in these Terms, to "in writing", this will include e-mail.</li>
        <li><b>16.2</b>If we have to contact you or give you notice in writing, we will do so by e-mail or by pre-paid post to the address you provide to us in your order.</li>
        <li><b>16.3</b>Please note that any notice given by you to us, or by us to you, will be deemed received and properly served 24 hours after an e-mail is sent, or three days after the date of posting of any letter. In proving the service of any notice, it will be sufficient to prove, in the case of a letter, that such letter was properly addressed, stamped and placed in the post and, in the case of an email, that such e-mail was sent to the specified e-mail address of the 9 addressee. The provisions of this clause shall not apply to the service of any proceedings or other documents in any legal action.</li>
    </ul>
</div>
<div class="term">
    <h4 class="title">17. Other important terms</h4>
    <ul class="terms-list">
        <li><b>17.1</b>We may transfer our rights and obligations under a Contract to another organisation, but this will not affect your rights or our obligations under these Terms.</li>
        <li><b>17.2</b>You may only transfer your rights or your obligations under these Terms to another person if we agree in writing.</li>
        <li><b>17.3</b>This contract is between you and us. No other person shall have any rights to enforce any of its terms, whether under the Contracts (Rights of Third Parties Act) 1999 or otherwise.</li>
        <li><b>17.4</b>Each of the paragraphs of these Terms operates separately. If any court or relevant authority decides that any of them are unlawful or unenforceable, the remaining paragraphs will remain in full force and effect.</li>
        <li><b>17.5</b>If we fail to insist that you perform any of your obligations under these Terms, or if we do not enforce our rights against you, or if we delay in doing so, that will not mean that we have waived our rights against you and will not mean that you do not have to comply with those obligations. If we do waive a default by you, we will only do so in writing, and that will not mean that we will automatically waive any later default by you.</li>
        <li><b>17.6</b>If you are a consumer, please note that these Terms are governed by English law. This means a Contract and any dispute or claim arising out of or in connection with it will be governed by English law. You and we both agree to that the courts of England and Wales will have non-exclusive jurisdiction. However, if you are a resident of Northern Ireland you may also bring proceedings in Northern Ireland, and if you are a resident of Scotland, you may also bring proceedings in Scotland.</li>
        <li><b>17.7</b>If you are a business, these Terms are governed by English law. This means that a Contract, and any dispute or claim arising out of or in connection with it or its subject matter or formation (including non-contractual disputes or claims), will be governed by English law. We both agree to the exclusive jurisdiction of the courts of England and Wales. Stonegate Precision Tooling Ltd, Melton House, Wyke Way, Melton, East Yorkshire, HU14 3HJ | 01482 620400 | www.stonegatetooling.com</li>
    </ul>
</div>
