<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
$icon = $block->getIcon();
$helper = $this->helper("Lof\RequestForQuote\Helper\Data");
$enable = $helper->isEnabledQuote();
$enable_miniquote = $helper->getConfig("general/enable_miniquote");
$enable_miniquote = ($enable_miniquote != null) ? (int)$enable_miniquote : 1;
if ($enable && $enable_miniquote) {
    ?>

    <div data-block="miniquote" class="miniquote-wrapper <?php if ($icon) : ?>has-icon<?php endif; ?>">
        <a class="action showquote" href="<?php /* @escapeNotVerified */
        echo $block->getShoppingCartUrl(); ?>"
           data-bind="scope: 'miniquote_content'">
            <?php echo $icon ?>
            <span class="counter qty empty"
                  data-bind="css: { empty: !!getQuoteParam('summary_count') == false }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: getQuoteParam('summary_count') --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: getQuoteParam('summary_count') -->
                <!-- ko text: getQuoteParam('summary_count') --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
                <!-- /ko -->
            </span>
        </span>
        </a>
        <?php if ($block->getIsNeedToDisplaySideBar()): ?>
            <div class="block block-miniquote empty"
                 data-role="dropdownDialog"
                 data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=miniquote]",
                "triggerTarget":".showquote",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
                <div id="miniquote-content-wrapper" data-bind="scope: 'miniquote_content'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
                <?php echo $block->getChildHtml('miniquote.addons'); ?>
            </div>
        <?php endif ?>
        <script>
            window.quotation = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
            if (typeof(window.checkout) === "undefined") {
                window.checkout = window.quotation;
            }
        </script>
        <script type="text/x-magento-init">
    {
        "[data-block='miniquote']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */
            echo $block->getJsLayout(); ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */
            echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }

        </script>
    </div>
<?php } ?>