<?php

$config = $block->getWysiwygConfig()->getConfig();
$config['height'] = '300px';
$config = json_encode($config->getData());

?>

<script>
    window.tinyMCE_GZ = window.tinyMCE_GZ || {}; window.tinyMCE_GZ.loaded = true;
    require(["jquery",
        "mage/translate",
        "mage/adminhtml/events",
        "Lof_RequestForQuote/js/wysiwyg/tiny_mce/setup",
        "mage/adminhtml/wysiwyg/widget"], function(jQuery){

            var initTask = setInterval(function(){
                init();
            }, 500);

            function init(){
                // if(document.getElementById("order-data").style.display !== "none"){ 
                    var config = <?php echo $config ?>;
                    var editor = [];
                    var editorFormValidationHandler;

                    jQuery.extend(config, {
                        settings: {
                            theme_advanced_buttons1: 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                            'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                            theme_advanced_buttons2: null,
                            theme_advanced_buttons3: null,
                            theme_advanced_buttons4: null
                        }
                    });

                    jQuery('.textarea.admin__control-textarea.wysiwyg-editor.admin__control-textarea').each(function () {
                        var elementId = jQuery(this).attr('id');
                        editor[elementId] = new rfqTinyMceWysiwygSetup(
                            elementId,
                            config
                        );

                        editorFormValidationHandler = editor[elementId].onFormValidation.bind(editor[elementId]);
                        Event.observe('toggle' + elementId, 'click', editor[elementId].toggle.bind(editor[elementId]));
                        Event.observe('toggle' + elementId, 'click', function () { jQuery('#toggle' + elementId).toggleClass('texteditor-enabled'); jQuery('.action-wysiwyg').toggleClass('hidden'); });
                        varienGlobalEvents.attachEventHandler('submitOrder', editorFormValidationHandler);
                        varienGlobalEvents.clearEventHandlers('open_browser_callback');
                        var currentEditor = editor[elementId];
                        varienGlobalEvents.attachEventHandler('open_browser_callback', currentEditor.openFileBrowser);

                        jQuery('#' + elementId)
                            .addClass('wysiwyg-editor')
                            .data(
                                'wysiwygEditor',
                                null
                            );

                        //Init Wysiwygeditor when start
                        editor[elementId].turnOn();
                        jQuery('#toggle' + elementId).toggleClass('texteditor-enabled');
                        jQuery('.action-wysiwyg').toggleClass('hidden');
                        //End Init Wysiwygeditor when start
                    });
                    clearInterval(initTask);
                // }
            }
        }
    );
</script>