<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Wishlist\Block\Cart\Item\Renderer\Actions\MoveToWishlist */
?>
<?php if ($block->isAllowInCart() && $block->isProductVisibleInSiteVisibility()): ?>
    <a href="#"
       data-post='<?php /* @escapeNotVerified */ echo $block->getMoveFromCartParams(); ?>'
       class="use-ajax action action-towishlist">
        <span><?php /* @escapeNotVerified */ echo __('Move to Wishlist'); ?></span>
        <i class="fa fa-heart" aria-hidden="true"></i>
    </a>
<?php else: ?>
    <a href="<?php echo $this->getUrl('customer/account/login'); ?>"
       class="action action-towishlist">
        <span><?php /* @escapeNotVerified */ echo __('Move to Wishlist'); ?></span>
        <i class="fa fa-heart" aria-hidden="true"></i>
    </a>
<?php endif; ?>
