<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base"><?php /* @escapeNotVerified */ echo __('Our Team') ?></span>
    </h1>
</div>
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('team_description')->toHtml(); ?>
<div class="team column-container colspan-4">
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/graham-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Graham Hazell</div>
                <div class="role">Director</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%20Graham%20Hazell" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <a href="https://www.linkedin.com/in/graham-hazell-56ab14115/" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/carl-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Carl Hazell</div>
                <div class="role">Operations Director</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%20Carl%20Hazell" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <a href="https://www.linkedin.com/in/carl-hazell-489649101/" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/jeremiah-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Jeremiah Clark</div>
                <div class="role">External Sales</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%20Jeremiah%20Clark" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <a href="https://www.linkedin.com/in/jeremiah-clark-5b49b8115/" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/lloyd-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Lloyd Johnston</div>
                <div class="role">External Sales</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%20Lloyd%20Johnston" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <a href="https://www.linkedin.com/in/lloyd-johnston-622a5bb0/" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/clayton-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Clayton Worsley</div>
                <div class="role">Commercial Manager</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%20Clayton%20Worsley" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <a href="https://www.linkedin.com/in/clayton-worsley-60973382/" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/denise-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Denise Stamper</div>
                <div class="role">Credit Control</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%20Denise%20Stamper" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <a href="#" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/lee-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Lee Winduss</div>
                <div class="role">Purchasing</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%20Lee%20Winduss" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <a href="https://www.linkedin.com/in/lee-winduss-659239a9/" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/dean-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Dean Carmichael</div>
                <div class="role">Warehouse & Despatch</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%20Dean%20Carmichael" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <a href="#" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/larry-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Larry Clark</div>
                <div class="role">Internal Sales</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%20Larry%20Clark" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <a href="https://www.linkedin.com/in/larry-clark-999a11115/" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/kirsty-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Kirtsy Paterson</div>
                <div class="role">Customer Service</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%Kirsty%20Paterson" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <!-- <a href="https://www.linkedin.com/in/lucilla-hazell-b28a13115/" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a> -->
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/jim-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Jim Worsley</div>
                <div class="role">Internal Sales & Customer Service</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%20Jim%20Worsley" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <a href="https://www.linkedin.com/in/jim-worsley-7639b5115/" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>

    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/dean-q-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Dean Quinton</div>
                <div class="role">Accounts</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%20Dean%20Quinton" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <a href="#" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/alan-min-2.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Alan Pollard</div>
                <div class="role">Operations Manager</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%20Alan%20Pollard" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <!-- <a href="https://www.linkedin.com/in/ben-campbell-06816385" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a> -->
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/darren-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Darren Kipling</div>
                <div class="role">Goods In</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%Darren%Kipling" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <!-- <a href="https://www.linkedin.com/in/ben-campbell-06816385" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a> -->
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/garth-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Garth Hazell</div>
                <div class="role">External Sales</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%20Garth%20Hazell" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <!-- <a href="https://www.linkedin.com/in/ben-campbell-06816385" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a> -->
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/keith-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Keith Barker</div>
                <div class="role">Internal Sales</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%Keith%20Barker" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <!-- <a href="https://www.linkedin.com/in/lucilla-hazell-b28a13115/" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a> -->
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/peta-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Peta Bean</div>
                <div class="role">Head of Marketing and Communications</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%Peta" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <!-- <a href="https://www.linkedin.com/in/lucilla-hazell-b28a13115/" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a> -->
                </div>
            </div>
        </div>
    </div>
    <div class="member column">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/katie-smith-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Katie Smith</div>
                <div class="role">Marketing &amp; Communications Coordinator</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%Katie%20Smith" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <!-- <a href="https://www.linkedin.com/in/lucilla-hazell-b28a13115/" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a> -->
                </div>
            </div>
        </div>
    </div>
    <div class="member column last">
        <div class="wrapper">
            <div class="image">
                <img src="<?php echo $this->getViewFileUrl('images/team/duncan-collie-min.jpg'); ?>" />
            </div>
            <div class="member-info">
                <div class="name">Duncan Collie</div>
                <div class="role">CNC Technician</div>
            </div>
            <div class="contact-links">
                <div class="links-wrapper">
                    <a href="mailto:info@stonegatetooling.com?subject=FAO%Duncan%20Collie" class="email"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    <a href="tel:<?php echo $block->getStoreTelephone(); ?>" class="tel"><i class="fa fa-phone" aria-hidden="true"></i></a>
                    <!-- <a href="https://www.linkedin.com/in/lucilla-hazell-b28a13115/" class="linked-in"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a> -->
                </div>
            </div>
        </div>
    </div>
    <div class="column filler"></div>
</div>