<?php /* @var $block Magento\Framework\View\Element\Template */ ?>

<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base">Trade Account Application</span>
    </h1>
</div>
<h3 class="subtitle">If you would like to open a Trade Account with Stonegate, please complete and submit the form
    below*</h3>
<p class="note">* Please note that completing this form does not automatically open your accounts.</p>
<form accept-charset="UTF-8" action="<?php echo $block->getUrl('requesttrade/index/post'); ?>" class="trade-application" id="form_tradeapplication" method="post">
    <fieldset class="fieldset column-container colspan-2">
        <div class="column">
            <h4 class="heading">Company Information</h4>
            <div class="field">
                <label class="label" for="full-company-title">Full Company Title<abbr title="required">*</abbr></label>
                <input type="text" id="full-company-title" required="required" name="form[full_company_title]"/>
            </div>
            <div class="field">
                <label class="label" for="registered-company-number">Registered Company
                    Number<abbr title="required">*</abbr></label>
                <input type="text" id="registered-company-number" required="required" name="form[registered_company_number]"/>
            </div>
            <div class="field">
                <label class="label" for="vat-no">Vat No<abbr title="required">*</abbr></label>
                <input type="text" id="vat-no" required="required" name="form[vat_no]"/>
            </div>
            <div class="field">
                <label class="label" for="tel-number">Tel Number<abbr title="required">*</abbr></label>
                <input type="tel" id="tel-number" required="required" name="form[tel_number]"/>
            </div>
            <div class="field">
                <label class="label" for="fax-number">Fax Number<abbr title="required">*</abbr></label>
                <input type="tel" id="fax-number" required="required" name="form[fax_number]"/>
            </div>
            <div class="field">
                <label class="label" for="email-address">Email Address<abbr title="required">*</abbr></label>
                <input type="email" id="email-address" required="required" name="form[email_address]"/>
            </div>
            <div class="field">
                <label class="label" for="web-address">Web Address<abbr title="required">*</abbr></label>
                <input type="text" id="web-address" required="required" name="form[web_address]"/>
            </div>
        </div>
        <div class="column">
            <h4 class="heading">Invoice Address</h4>
            <div class="field">
                <label class="label" for="address-line-1">Address Line 1<abbr title="required">*</abbr></label>
                <input type="text" id="address-line-1" required="required" name="form[invoice_address_line_1]"/>
            </div>
            <div class="field">
                <label class="label" for="address-line-1">Address Line 2</label>
                <input type="text" id="address-line-2" name="form[invoice_address_line_2]"/>
            </div>
            <div class="field">
                <label class="label" for="town-city">Town/City<abbr title="required">*</abbr></label>
                <input type="text" id="town-city" required="required" name="form[invoice_town_city]"/>
            </div>
            <div class="field">
                <label class="label" for="county">County<abbr title="required">*</abbr></label>
                <input type="text" id="county" required="required" name="form[invoice_county]"/>
            </div>
            <div class="field">
                <label class="label" for="country">Country<abbr title="required">*</abbr></label>
                <input type="text" id="country" required="required" name="form[invoice_country]"/>
            </div>
            <div class="field">
                <label class="label" for="postcode">Postcode<abbr title="required">*</abbr></label>
                <input type="text" placeholder="Postcode" id="postcode" required="required" name="form[invoice_postcode]"/>
            </div>
            <div class="field checkbox">
                <input type="checkbox" id="delivery-address-check" name="form[delivery_address_check]"/>
                <label class="label" for="delivery-address-check">Please check if your delivery address is different to
                    your invoice address.</label>
            </div>
        </div>
        <div class="column" id="delivery-address-fields">
            <h4 class="heading">Delivery Address</h4>
            <div class="field">
                <label class="label" for="delivery-address-line-1">Address Line 1</label>
                <input type="text" id="delivery-address-line-1" name="form[delivery_address_line_1]"/>
            </div>
            <div class="field">
                <label class="label" for="delivery-address-line-1">Address Line 2</label>
                <input type="text" id="delivery-address-line-2" name="form[delivery_address_line_2]"/>
            </div>
            <div class="field">
                <label class="label" for="delivery-town-city">Town/City</label>
                <input type="text" id="delivery-town-city" name="form[delivery_town_city]"/>
            </div>
            <div class="field">
                <label class="label" for="delivery-county">County</label>
                <input type="text" id="delivery-county" name="form[delivery_county]"/>
            </div>
            <div class="field">
                <label class="label" for="delivery-country">Country</label>
                <input type="text" id="delivery-country" name="form[delivery_country]"/>
            </div>
            <div class="field">
                <label class="label" for="delivery-postcode">Postcode</label>
                <input type="text" placeholder="Postcode" id="delivery-postcode" name="form[delivery_postcode]"/>
            </div>
        </div>
    </fieldset>
    <h3 class="title">Limited Company</h3>
    <fieldset class="fieldset column-container colspan-2">
        <div class="column">
            <div class="field">
                <label class="label" for="limited-director-name">Name of Director(s)</label>
                <input type="text" id="limited-director-name" name="form[limited_director_name]"/>
            </div>
            <div class="field">
                <label class="label" for="limited-registration-number">Registration Number</label>
                <input type="text" id="limited-registration-number" name="form[limited_registration_number]"/>
            </div>
            <div class="field">
                <label class="label" for="limited-date-formation">Date of Formation</label>
                <input type="text" id="limited-date-formation" required="required" name="form[limited_date_formation]"/>
            </div>
            <div class="field">
                <label class="label" for="accounts-email">Parent or Associated Companies</label>
                <input type="text" id="accounts-email" name="form[accounts_email]"/>
            </div>
            <div class="field checkbox">
                <input type="checkbox" id="limited-address-check" name="form[limited_address_check]"/>
                <label class="label" for="limited-address-check">Please check if your limited company address is
                    different to your invoice address.</label>
            </div>
        </div>
        <div class="column" id="limited-address-fields">
            <div class="field">
                <label class="label" for="limited-address-line-1">Address Line 1</label>
                <input type="text" id="limited-address-line-1" name="form[limited_address_line_1]"/>
            </div>
            <div class="field">
                <label class="label" for="limited-address-line-1">Address Line 2</label>
                <input type="text" id="limited-address-line-2" name="form[limited_address_line_2]"/>
            </div>
            <div class="field">
                <label class="label" for="limited-town-city">Town/City</label>
                <input type="text" id="limited-town-city" name="form[limited_town_city]"/>
            </div>
            <div class="field">
                <label class="label" for="limited-county">County</label>
                <input type="text" id="limited-county" name="form[limited_county]"/>
            </div>
            <div class="field">
                <label class="label" for="limited-country">Country</label>
                <input type="text" id="limited-country" name="form[limited_country]"/>
            </div>
            <div class="field">
                <label class="label" for="limited-postcode">Postcode</label>
                <input type="text" placeholder="Postcode" id="limited-postcode" name="form[limited_postcode]"/>
            </div>
        </div>
    </fieldset>
    <h3 class="title">Sole Trader / Partnership (please add as applicable)</h3>
    <fieldset class="fieldset column-container colspan-3 sole-trader-wrapper">
        <div class="column" id="sole-trader" data-index="1">
            <div class="field">
                <label class="label">Name of Director</label>
                <input type="text" data-nametemplate="form[trader][REPLACE][name]" name="form[trader][1][name]"/>
            </div>
            <div class="field">
                <label class="label">Date of Birth</label>
                <input type="text" id="trader-dob" data-nametemplate="form[trader][REPLACE][dob]" name="form[trader][1][dob]"/>
            </div>
            <div class="field">
                <label class="label">Home Address</label>
                <input type="text" data-nametemplate="form[trader][REPLACE][address]" name="form[trader][1][address]"/>
            </div>
            <div class="field">
                <label class="label">Tel Number</label>
                <input type="tel" data-nametemplate="form[trader][REPLACE][tel]" name="form[trader][1][tel]"/>
            </div>
        </div>
    </fieldset>
    <div class="action primary add-trader"><span>Add Sole Trader / Partnership</span></div>
    <h3 class="title">Accounts</h3>
    <fieldset class="fieldset column-container colspan-2">
        <div class="column">
            <div class="field">
                <label class="label" for="accounts-contact">Contact Name<abbr title="required">*</abbr></label>
                <input type="text" id="accounts-contact" required="required" name="form[accounts_contact]"/>
            </div>
            <div class="field">
                <label class="label" for="accounts-tel">Tel Number<abbr title="required">*</abbr></label>
                <input type="text" id="accounts-tel" required="required" name="form[accounts_tel]"/>
            </div>
            <div class="field">
                <label class="label" for="accounts-fax">Fax Number<abbr title="required">*</abbr></label>
                <input type="text" id="accounts-fax" required="required" name="form[accounts_fax]"/>
            </div>
            <div class="field">
                <label class="label" for="accounts-email">Email<abbr title="required">*</abbr></label>
                <input type="text" id="accounts-email" required="required" name="form[accounts_email]"/>
            </div>
            <div class="field checkbox">
                <input type="checkbox" id="email-invoice-check" name="form[email_invoice_check]"/>
                <label class="label" for="email-invoice-check">We prefer to send invoices & statements by email. Please
                    select here if you do not wish to receive these by email.</label>
            </div>
        </div>
        <div class="column">
            <div class="field">
                <label class="label" for="accounts-bank">Bank Name<abbr title="required">*</abbr></label>
                <input type="text" id="accounts-bank" required="required" name="form[accounts_bank_name]"/>
            </div>
            <div class="field">
                <label class="label" for="accounts-bank-address">Bank Address<abbr title="required">*</abbr></label>
                <input type="text" id="accounts-bank-address" required="required" name="form[accounts_bank_address]"/>
            </div>
            <div class="field">
                <label class="label" for="accounts-sort-code">Sort Code<abbr title="required">*</abbr></label>
                <input type="text" id="accounts-sort-code" required="required" name="form[accounts_sort_code]"/>
            </div>
            <div class="field">
                <label class="label" for="accounts-credit-limit-requested">Credit Limit Requested<abbr title="required">*</abbr></label>
                <input type="text" id="accounts-credit-limit-requested" required="required" name="form[accounts_credit_limit]"/>
            </div>
            <div class="field">
                <label class="label" for="account-number">Account Number</label>
                <input type="number" id="account-number" name="form[accounts_account_number]"/>
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset column-container colspan-2">
        <div class="column">
            <h3 class="title">Trade Reference 1</h3>
            <div class="field">
                <label class="label" for="red-1-company-name">Company Name<abbr title="required">*</abbr></label>
                <input type="text" id="ref-1-company-name" required="required" name="form[ref_1_company_name]"/>
            </div>
            <div class="field">
                <label class="label" for="contact-person">Contact Person<abbr title="required">*</abbr></label>
                <input type="text" id="ref-1-contact-person" required="required" name="form[ref_1_contact_person]"/>
            </div>
            <div class="field">
                <label class="label" for="red-1-address">Address<abbr title="required">*</abbr></label>
                <input type="text" id="red-1-address" required="required" name="form[ref_1_address]"/>
            </div>
            <div class="field">
                <label class="label" for="red-1-telephone">Telephone<abbr title="required">*</abbr></label>
                <input type="tel" id="red-1-telephone" required="required" name="form[ref_1_telephone]"/>
            </div>
        </div>
        <div class="column">
            <h3 class="title">Trade Reference 2</h3>
            <div class="field">
                <label class="label" for="red-2-company-name">Company Name<abbr title="required">*</abbr></label>
                <input type="text" id="ref-2-company-name" required="required" name="form[ref_2_company_name]"/>
            </div>
            <div class="field">
                <label class="label" for="contact-person">Contact Person<abbr title="required">*</abbr></label>
                <input type="text" id="ref-2-contact-person" required="required" name="form[ref_2_contact_person]"/>
            </div>
            <div class="field">
                <label class="label" for="red-2-address">Address<abbr title="required">*</abbr></label>
                <input type="text" id="red-2-address" required="required" name="form[ref_2_address]"/>
            </div>
            <div class="field">
                <label class="label" for="red-2-telephone">Telephone<abbr title="required">*</abbr></label>
                <input type="tel" id="red-2-telephone" required="required" name="form[ref_2_telephone]"/>
            </div>
        </div>
    </fieldset>
    <div class="credit-terms">
        <h3 class="subtitle">Credit Terms & Conditions</h3>
        <div>
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('credit_terms_conditions')->toHtml(); ?>
        </div>
    </div>
    <fieldset class="fieldset column-container colspan-2 last">
        <div class="column">
            <div class="field">
                <label class="label" for="name">Name<abbr title="required">*</abbr></label>
                <input type="text" id="name" required="required" name="form[name]"/>
            </div>
            <div class="field">
                <label class="label" for="date">Date<abbr title="required">*</abbr></label>
                <input type="text" id="date" required="required" name="form[date]"/>
            </div>
        </div>
        <div class="column">
            <div class="field">
                <label class="label" for="title">Title<abbr title="required">*</abbr></label>
                <input type="text" id="title" required="required" name="form[title]"/>
            </div>
            <div class="field checkbox">
                <input type="checkbox" id="terms-agreement" name="form[terms_agreement]"/>
                <label class="label" for="terms-agreement">I have read and accept Stonegate's
                    <a target="_blank" href="<?php echo $this->getUrl('general-terms-conditions-of-sale'); ?>">terms and
                        conditions of sale</a>, and
                    <a target="_blank" href="<?php echo $this->getUrl('website-terms-conditions-of-sale'); ?>">website
                        terms and conditions</a><abbr title="required">*</abbr></label>
            </div>
        </div>
    </fieldset>
    <button type="submit" title="Submit" class="action submit primary large">
        <span>Submit</span>
    </button>
</form>
<script>
    requirejs(['jquery'], function ($) {
        $('#delivery-address-check').change(function () {
            if ($('#delivery-address-check').is(':checked')) {
                $('#delivery-address-fields').show();
            } else {
                $('#delivery-address-fields').hide();
            }
        });
        $('#limited-address-check').change(function () {
            if ($('#limited-address-check').is(':checked')) {
                $('#limited-address-fields').show();
            } else {
                $('#limited-address-fields').hide();
            }
        });

        var regex = /^(.+?)(\d+)$/i;
        var cloneIndex = $('#sole-trader').length;

        function clone() {
            $('#sole-trader').clone()
                .appendTo('.sole-trader-wrapper')
                .attr('id', 'sole-trader' + cloneIndex)
                .find('input')
                .each(function () {
                    var name = $(this).attr('name');
                    var template = $(this).data('nametemplate').replace('REPLACE', cloneIndex + 1);

                    $(this).attr('name', template);
                })
                .on('click', '.action.add-trader', clone)
                .on('click', 'button.remove', remove);
            cloneIndex++;
        }

        $('.action.add-trader').on('click', clone);
    });
</script>