<?php /* @var $block Magento\Framework\View\Element\Template */ ?>

<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base"><?php /* @escapeNotVerified */ echo __('Trade Account Application') ?></span>
    </h1>
</div>

<div class="header"><?php echo __('Thanks for your application'); ?></div>

<div class="content">
    <p><?php echo __('We normally respond to trade account applications within 48 hours. You will receive an email to verify your account. Please follow the instructions on this email to activate your account and begin placing orders on a trade account basis. If you have not received an emil within 48 hours, please check your junk mailbox, or email us on accounts@stonegatetooling.co.uk'); ?></p>
    <br/>
    <p><?php echo __('If you need to place an order in the meantime, you can do this with your registered account, however, immediate payment will be required.'); ?></p>
</div>