<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?php echo $block->getChildHtml('form_before') ?>
<form action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/updatePost') ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'
          class="form form-cart">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <div class="cart table-wrapper<?php echo $mergedCells == 2 ? ' detailed' : ''; ?>">
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption role="heading" aria-level="2" class="table-caption"><?php /* @escapeNotVerified */ echo __('Shopping Cart Items') ?></caption>
            <thead>
                <tr>
                    <th class="col image" scope="col"><span><?php /* @escapeNotVerified */ echo __('Image') ?></span></th>
                    <th class="col item" scope="col"><span><?php /* @escapeNotVerified */ echo __('Product Name') ?></span></th>
                    <th class="col edit" scope="col"><span><?php /* @escapeNotVerified */ echo __('Edit') ?></span></th>
                    <th class="col qty" scope="col"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></th>
                    <th class="col price" scope="col"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span></th>
                    <th class="col subtotal" scope="col"><span><?php /* @escapeNotVerified */ echo __('Subtotal') ?></span></th>
                </tr>
            </thead>
            <?php foreach ($block->getItems() as $_item): ?>
                <?php echo $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </table>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        require(['jquery'], function($){
            var responsiveCart = {
                onResize: function () {
                    $(window).resize(function () {
                        responsiveCart.checkWidth();
                    });
                },
                checkWidth: function () {
                    if (window.innerWidth > 768) {
                        responsiveCart.desktop();
                    } else {
                        responsiveCart.mobile();
                    }
                },
                desktop: function () {

                },
                mobile: function () {
                    $('.item-info .col.price, .item-info .col.subtotal, .item-info .col.qty').each(function() {
                        var destination = $(this).parent('tr.item-info').find('.col.item .mobile-content');
                        $(this).appendTo(destination);
                    });
                    $('.item-info .edit-tools').each(function() {
                        var destination = $(this).parent('tr.item-info').find('.col.item');
                        $(this).appendTo(destination);
                    });
                },
                init: function () {
                    this.onResize();
                    this.checkWidth();
                }
            };
            responsiveCart.init();
        });
        //]]>
    </script>
    <div class="cart free-delivery">
        <?php echo $this->getLayout()->createBlock('AudereCommerce\Stonegate\Block\StoreInfo')->setTemplate('Magento_Checkout::cart/freedelivery.phtml')->toHtml(); ?>
    </div>
    <div class="cart main actions">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="action continue"
               href="<?php echo $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?php echo $block->escapeHtml(__('Continue Shopping')); ?>">
                <span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span>
            </a>
        <?php endif; ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?php echo $block->escapeHtml(__('Clear Shopping Cart')); ?>"
                class="action clear" id="empty_cart_button">
            <span><?php /* @escapeNotVerified */ echo __('Clear Shopping Cart'); ?></span>
        </button>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?php echo $block->escapeHtml(__('Update Shopping Cart')); ?>"
                class="action update">
            <span><?php /* @escapeNotVerified */ echo __('Update Shopping Cart'); ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?php echo $block->getChildHtml('checkout.cart.order.actions') ?>
<?php echo $block->getChildHtml('shopping.cart.table.after'); ?>

