<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item                    = $block->getItem();
$product                  = $_item->getProduct();
$isVisibleProduct         = $product->isVisibleInSiteVisibility();
$helper                   = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp             = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$cartHelper               = $this->helper('Magento\Checkout\Helper\Cart');
$deletePostJson           = $cartHelper->getDeletePostJson($_item);
$deletePostJson           = json_decode($deletePostJson, true);
$deletePostJson['action'] = str_replace("checkout/cart/", "quotation/cart/", $deletePostJson['action']);
$rfqHelper                = $this->helper('Lof\RequestForQuote\Helper\Data');
$quote                    = $_item->getQuote();
$currency_code            = $quote?$quote->getQuoteCurrencyCode():null;
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?php echo $block->escapeHtml(__('Item')); ?>" class="col item">
            <?php if ($block->hasProductUrl()):?>
                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"
                 title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
                 tabindex="-1"
                 class="product-item-photo">
             <?php else:?>
                <span class="product-item-photo">
                <?php endif;?>
                <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
                <?php if ($block->hasProductUrl()):?>
                </a>
            <?php else: ?>
            </span>
        <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <span><?php echo __('Product Name: '); ?></span>
                <?php if ($block->hasProductUrl()):?>
                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?php echo $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()):?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?php /* @escapeNotVerified */ echo $message['type'] ?>"><div><?php echo $block->escapeHtml($message['text']) ?></div></div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
            <p>
                <?php echo strip_tags($_item->getDescription()); ?>
            </p>
        </div>
    </td>
    <td class="col sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>">
        <?php /* @escapeNotVerified */ echo $_item->getSku() ?>
    </td>
    <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php echo $rfqHelper->formatPrice($_item->getRowTotal(), false, $currency_code) ?>
    </td>
    <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
        <div class="field qty">
            <div class="control qty">
                <?php /* @escapeNotVerified */ echo $block->getQty() ?>
            </div>
        </div>
    </td> 
</tr>
</tbody>
