<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile



$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$cartHelper = $this->helper('Magento\Checkout\Helper\Cart');
$deletePostJson = $cartHelper->getDeletePostJson($_item);
$deletePostJson = json_decode($deletePostJson, true);
$deletePostJson['action'] = str_replace("checkout/cart/", "quotation/cart/", $deletePostJson['action']);
$rfqHelper = $this->helper('Lof\RequestForQuote\Helper\Data');
$currentcySymbol = $rfqHelper->getCurrentCurrencySymbol();
$enable_price = $rfqHelper->getConfig("general/enable_price");
if ($enable_price == '' || $enable_price == null) {
    $enable_price = 1;
}
$enable_edit_price = $rfqHelper->getConfig("general/enable_edit_price");
if ($enable_edit_price == '' || $enable_edit_price == null) {
    $enable_edit_price = 1;
}


$configureUrl = \Magento\Framework\App\ObjectManager::getInstance()->create('\Magento\Framework\Url')->getUrl(
    'quotation/quote/configure',
    ['id' => $_item->getId(), 'product_id' => $_item->getProduct()->getId()]
);
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?php echo $block->escapeHtml(__('Item')); ?>" class="col item">
        <?php if ($block->hasProductUrl()): ?>
        <a href="<?php /* @escapeNotVerified */
        echo $block->getProductUrl() ?>"
           title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">
            <?php else: ?>
            <span class="product-item-photo">
                <?php endif; ?>
                <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
                <?php if ($block->hasProductUrl()): ?>
        </a>
    <?php else: ?>
        </span>
    <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?php /* @escapeNotVerified */
                    echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?php echo $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()): ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?php /* @escapeNotVerified */
                                echo $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?php /* @escapeNotVerified */
                                echo $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?php /* @escapeNotVerified */
                    echo $message['type'] ?>">
                        <div><?php echo $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif; ?>

            <p>
            <div class="rfq-addnote"
                 <?php if ($_item->getDescription()) { ?>style="display:none"<?php } ?>><?php echo __('Add Note'); ?></div>
            <textarea <?php if ($_item->getDescription()) { ?>style="display:block"<?php } ?> class="rfq-description"
                      name="cart[<?php /* @escapeNotVerified */
                      echo $_item->getId() ?>][description]"><?php echo $_item->getDescription(); ?></textarea>
            </p>
        </div>
    </td>
    <?php if ($enable_price) { ?>
        <?php if ($canApplyMsrp): ?>
            <td class="col msrp" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
            <span class="pricing msrp">
                <span class="msrp notice"><?php /* @escapeNotVerified */
                    echo __('See price before order confirmation.'); ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a href="#" class="action help map" id="<?php /* @escapeNotVerified */
                echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */
                echo $helpLinkId; ?>","productName": "<?php /* @escapeNotVerified */
                echo $product->getName(); ?>","showAddToCart": false}}'>
                    <span><?php /* @escapeNotVerified */
                        echo __("What's this?"); ?></span>
                </a>
            </span>
            </td>
        <?php else: ?>
            <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                <?php if ($enable_edit_price) { ?>
                    <span><input id="cart-<?php /* @escapeNotVerified */
                        echo $_item->getId() ?>-customprice"
                                 name="cart[<?php /* @escapeNotVerified */
                                 echo $_item->getId() ?>][customprice]"
                                 data-cart-item-id="<?php /* @escapeNotVerified */
                                 echo $_item->getSku() ?>"
                                 value="<?php /* @escapeNotVerified */
                                 echo $_item->getCustomPrice() ? $_item->getCustomPrice() : $_item->getPrice() ?>"
                                 type="number"
                                 size="4"
                                 title="<?php echo $block->escapeHtml(__('Price')); ?>"
                                 class="input-text customprice"
                                 maxlength="12"
                                 data-validate="{required:true,'validate-greater-than-zero':true}"
                                 data-role="cart-item-customprice"/></span>
                    <span><?php echo $currentcySymbol ?></span>
                <?php } else { ?>
                    <span><?php /* @escapeNotVerified */
                        $row_price = $_item->getCustomPrice() ? $_item->getCustomPrice() : $_item->getPrice();
                        echo $rfqHelper->formatPriceWithCurency($row_price); ?></span>
                <?php } ?>
            </td>
        <?php endif; ?>
    <?php } else { ?>
        <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">

        </td>
    <?php } ?>
    <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
        <div class="field qty">
            <label class="label" for="cart-<?php /* @escapeNotVerified */
            echo $_item->getId() ?>-qty">
                <span><?php /* @escapeNotVerified */
                    echo __('Qty') ?></span>
            </label>
            <div class="control qty">
                <input id="cart-<?php /* @escapeNotVerified */
                echo $_item->getId() ?>-qty"
                       name="cart[<?php /* @escapeNotVerified */
                       echo $_item->getId() ?>][qty]"
                       data-cart-item-id="<?php /* @escapeNotVerified */
                       echo $_item->getSku() ?>"
                       value="<?php /* @escapeNotVerified */
                       echo $block->getQty() ?>"
                       type="number"
                       size="4"
                       title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                       class="input-text qty"
                       maxlength="12"
                       data-validate="{required:true,'validate-greater-than-zero':true}"
                       data-role="cart-item-qty"/>
            </div>
        </div>
    </td>
</tr>
<tr class="item-actions">
    <td colspan="100">
        <div class="actions-toolbar">
            <a class="action action-edit"
               href="<?= /* @escapeNotVerified */
               $configureUrl ?>"
               title="<?= $block->escapeHtml(__('Edit item parameters')) ?>">
                <span>
                    <?= /* @escapeNotVerified */
                    __('Edit') ?>
                </span>
            </a>
            <a href="#"
               title="<?php echo $block->escapeHtml(__('Remove item')); ?>"
               class="action action-delete"
               data-post='<?php /* @escapeNotVerified */
               echo json_encode($deletePostJson); ?>'>
            <span>
                <?php /* @escapeNotVerified */
                echo __('Remove item') ?>
            </span>
            </a>
        </div>
    </td>
</tr>
</tbody>
