<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Account Information') ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ echo __('Contact Information') ?></span>
            </strong>
            <div class="box-content">
                <p>
                    <?php echo $block->escapeHtml($block->getName()) ?><br>
                    <?php echo $block->escapeHtml($block->getCustomer()->getEmail()) ?><br>
                </p>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getUrl('customer/account/edit') ?>">
                    <span><?php /* @escapeNotVerified */ echo __('Edit') ?></span>
                </a>
                <a href="<?php /* @escapeNotVerified */ echo $block->getChangePasswordUrl() ?>" class="action change-password">
                    <?php /* @escapeNotVerified */ echo __('Change Password') ?>
                </a>
            </div>
        </div>
        <div class="box actions">
            <a href="<?php echo $this->getUrl('sales/order/history'); ?>" class="action primary"><span>View Previous Orders</span></a>
        </div>
    </div>
</div>
