<div class="page-main section about-trade">
    <div class="column-container">
        <div class="column-2-3">
            <h2 class="title">Stonegate Trade Account</h2>
            <div class="subtitle">Enjoy doing business easily with your online Stonegate Trade Account:</div>
            <ul>
                <li>Access your account, terms and trade online for next day delivery where available</li>
                <li>View the details of your account and edit the details 24/7, whenever you need to</li>
                <li>30 Day credit</li>
                <li>Thousands of products in-stock and available for next-day or same day delivery</li>
                <li>Personalised terms on the products you buy</li>
                <li>Targeted special offers</li>
                <li>Nationwide technical support on +44 (0) 1482 620400 and face-to-face coverage through our technical representatives</li>
            </ul>
        </div>
        <div class="column-1-3">
            <div class="action-box">
                <div class="text">Ready to experience the benefits of a Stonegate trade account?</div>
                <a href="<?php echo $this->getUrl('requesttrade'); ?>" class="action primary">Apply Now</a>
            </div>
            <div class="action-box">
                <div class="text">Already an offline trade customer? Contact us to get your exclusive online trade account details.</div>
                <a href="<?php echo $this->getUrl('contact'); ?>" class="action primary">Contact Us</a>
            </div>
        </div>
    </div>
</div>