<?php
/** @var \Magento\Backend\Block\Template $block */
?>

<h2 class="feefo-error-heading"><?php echo __("Something went wrong..."); ?></h2>
<div class="feefo-error-wrapper">
    <p><?php echo __("It seems like something went wrong during the installation of the Feefo Plugin or loading of the configuration page."); ?></p>
    <p><?php echo __("Please try to install the app again or contact <a href='mailto:technical@feefo.com?subject=Feefo Plugin Installation Issue' title='Contact us asking for help'>the Feefo Support Team</a> if you still encounter issues with the installation process.") ?></p>
</div>