<ul class="social-links">
    <li>
		<a href="https://www.facebook.com/Stonegatetool/">
			<i class="fa fa-facebook"></i>
		</a>
    </li>
    <li>
        <a href="https://twitter.com/stonegatetool?lang=en">
			<i class="fa fa-twitter"></i>
		</a>
    </li>
    <li>
		<a href="https://www.linkedin.com/company/stonegate-precision-tooling-ltd">
			<i class="fa fa-linkedin"></i>
		</a>
    </li>
</ul>