<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */
?>
<?php 
$dataHelper                  = $this->helper("Lof\RequestForQuote\Helper\Data"); 
$enable_quote = $dataHelper->isEnabledQuote();
$enable_addtoquote = $dataHelper->getConfig('general/enable_addtoquote');
$enable_addtoquote = ($enable_addtoquote !==null)?(int)$enable_addtoquote:1;
$disable_addtocart = $dataHelper->getConfig('general/disable_addtocart');
$disable_addtocart = ($disable_addtocart !==null)?(int)$disable_addtocart:0;
?>
<?php $_total = $block->getItems()->getSize() ?>
<?php if ($_total): ?>
    <a href="#" class="action print" title="<?php /* @escapeNotVerified */ echo __('Print This Page') ?>">
        <span><?php /* @escapeNotVerified */ echo __('Print This Page') ?></span>
    </a>
        <div class="table-wrapper comparison">
            <table class="data table table-comparison" id="product-comparison"
                data-mage-init='{"compareList":{
                    "windowPrintSelector":".action.print",
                    "productsInRow":"5",
                    "selectors":{
                        "productAddToCartSelector":"button.action.tocart"}
                }}'>
                <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Compare Products') ?></caption>
                <thead>
                <tr>
                    <?php $_i = 0 ?>
                    <?php foreach ($block->getItems() as $_item): ?>
                        <?php if ($_i++ == 0): ?>
                            <th scope="row" class="cell label remove"><span><?php /* @escapeNotVerified */ echo __('Remove Product') ?></span></th>
                        <?php endif; ?>
                        <td class="cell remove product">
                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                            <a href="#" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataRemove($_item); ?>'
                               class="action delete" title="<?php /* @escapeNotVerified */ echo __('Remove Product') ?>">
                                <span><?php /* @escapeNotVerified */ echo __('Remove Product') ?></span>
                            </a>
                        </td>
                    <?php endforeach; ?>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <?php $_i = 0; ?>
                    <?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
                    <?php /** @var $_item \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($block->getItems() as $_item): ?>
                        <?php 
                            $is_disable_addtocart = $dataHelper->isDisabledAddTocart($_item);
                            $is_enable_addtoquote = $dataHelper->isEnabledAddToQuote($_item, true);
                        ?>
                        <?php if ($_i++ == 0): ?>
                            <th scope="row" class="cell label product"><span><?php /* @escapeNotVerified */ echo __('Product') ?></span></th>
                        <?php endif; ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Product')); ?>" class="cell product info">
                            <a class="product-item-photo" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php /* @escapeNotVerified */ echo $block->stripTags($_item->getName(), null, true) ?>">
                                <?php echo $block->getImage($_item, 'product_comparison_list')->toHtml(); ?>
                            </a>
                            <strong class="product-item-name">
                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php /* @escapeNotVerified */ echo $block->stripTags($_item->getName(), null, true) ?>">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_item, $_item->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?php echo $block->getReviewsSummaryHtml($_item, 'short') ?>
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item, '-compare-list-top') ?>
                            <div class="product-item-actions">
                                <div class="actions-primary">
                                    <?php if ($_item->isSaleable()): ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product\Compare')->getAddToCartUrl($_item); ?>" method="post">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <?php if($is_disable_addtocart) { 
                                                //Do nothing
                                            } else{ 
                                            ?>
                                            <button type="submit" class="action tocart primary">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart'); ?></span>
                                            </button>
                                            <?php } ?>
                                            <?php if ($is_enable_addtoquote) { ?>
                                            <?php $buttonTitle = __('Add to Quote'); ?>
                                           
                                            <button type="submit"
                                                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                                                            class="action primary toquote product-addtoquote-button">
                                                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                                            </button>
                                           
                                            <?php } ?>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_item->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                    <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>' class="action towishlist" data-action="add-to-wishlist">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                        </a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </td>
                    <?php endforeach; ?>
                </tr>
                </tbody>
                <tbody>
                <?php foreach ($block->getAttributes() as $_attribute): ?>
                    <tr>
                        <?php $_i = 0 ?>
                        <?php foreach ($block->getItems() as $_item): ?>
                            <?php if ($_i++ == 0): ?>
                                <th scope="row" class="cell label">
                                    <span class="attribute label">
                                        <?php echo $block->escapeHtml($_attribute->getStoreLabel() ? $_attribute->getStoreLabel() : __($_attribute->getFrontendLabel())) ?>
                                    </span>
                                </th>
                            <?php endif; ?>
                            <td class="cell product attribute">
                                <div class="attribute value">
                                    <?php switch ($_attribute->getAttributeCode()) {
                                        case "price": ?>
                                            <?php
                                                /* @escapeNotVerified */ echo $block->getProductPrice(
                                                    $_item,
                                                    '-compare-list-' . $_attribute->getCode()
                                                )
                                            ?>
                                            <?php break;
                                        case "small_image": ?>
                                            <?php $block->getImage($_item, 'product_small_image')->toHtml(); ?>
                                            <?php break;
                                        default: ?>
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_item, $block->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?>
                                        <?php break;
                                    } ?>
                                </div>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
         <script >
            require([
                'jquery',
                'mage/mage',
                'Magento_Catalog/js/catalog-add-to-cart',
                'Lof_RequestForQuote/js/catalog-add-to-quote'
            ], function($) {
                'use strict'
                var addToQuote = false;
            
                
                $('.product-addtoquote-button').each(function() { 
                   
                    $(this).on( "click",function () {
                        addToQuote = $(this).closest('form[data-role=tocart-form]').attr('action').replace("checkout/cart/add", "quotation/cart/add");
                      
                    });
                   
                    $(this).next().on( "click",function () {
                        var addToQuote = false;
                    });
                    $(this).closest('form[data-role=tocart-form]').mage('validation', {
                        radioCheckboxClosest: '.nested',
                        submitHandler: function (form) {
                            if (addToQuote) {
                                var widget = $(form).catalogAddToQuote({
                                    bindSubmit: false,
                                    quoteFormUrl: addToQuote
                                });
                                widget.catalogAddToQuote('submitForm', $(form));
                                addToQuote = false;
                            } else {
                                 var widget = $(form).catalogAddToCart({bindSubmit: false});
                                widget.catalogAddToCart('submitForm', $(form));
                            }
                            return false;
                        }
                    });            
                });            
            });

       
        </script>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <!-- <script type="text/x-magento-init">
            {
                "[data-role=tocart-form]": {
                    "catalogAddToCart": {}
                }
            }
            </script> -->
        <?php endif; ?>
<?php else: ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('You have no items to compare.') ?></div></div>
<?php endif; ?>
