<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base"><?php /* @escapeNotVerified */ echo __('Frequently Asked Questions') ?></span>
    </h1>
</div>
<h3 class="title">General</h3>
<div class="faq-container">
    <div class="faq">
        <div class="question">
            <h5>Can I speak to your Customer Care Team?</h5>
        </div>
        <div class="answer">
            <p>Of course! Simply call +44 (0) 1482 620400, who are by the phones between 07:00 – 16:00, Monday to Friday and are more than happy to help with every enquirey be it sales of technical support.</p>
            <p>If you would rather get in touch via email, you can reach us at <a href="mailto:info@stonegatetooling.co.uk">info@stonegatetooling.co.uk.</a></p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>Why is it asking me to Sign In / Save my Details?</h5>
        </div>
        <div class="answer">
            <p>We ask you to Sign In to make buying online with us quicker and easier. Through saving your details with us we can securely save your details to allow you to checkout much quicker.</p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>What is a Trade Account?</h5>
        </div>
        <div class="answer">
            <p>A Trade Account is for business customers who purchase with us frequently, usually on credit terms. Trade Account customers benefit from being able to save their details online, manage other users on the business account, view order history, manage addresses and pay invoices. </p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>I’ve forgotten my password! Help!?</h5>
        </div>
        <div class="answer">
            <p>On the log in page, simply click ‘Forgotten Password’. This will direct you to a helpful form where you can change your password and gain access to your account! </p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>I have a new credit/debit card, how do I amend my details to buy online?</h5>
        </div>
        <div class="answer">
            <p>Simply sign-in as usual and add items to your basket before proceeding to the checkout. When you are in the checkout stage, change the saved card details and continue with your purchase. If you are a Trade Account customer you can manage your payment details for both card and credit in your account section. </p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>How do I know if my promotional code has worked?</h5>
        </div>
        <div class="answer">
            <p>When you enter a promotional code at checkout stage you will see that a flag telling you that the code has been accepted and the discount applied.</p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>Why is my item delayed or on back-order?</h5>
        </div>
        <div class="answer">
            <p>We stock one of the UK’s largest ranges of specialist products for the stone and composite industries and dispatch thousands of items every day. It’s our goal to continue to have one of the most comprehensive ranges of in-stock items in the industry but sometimes we be waiting on stock into our depots.</p>
            <p>If your item is delayed or on back-order, we ship it as soon as it is delivered to us to ensure you get it was soon as possible and aim to keep you updated as to the progress of your order.</p>
        </div>
    </div>
</div>
<h3 class="title">Delivery & Returns</h3>
<div class="faq-container">
    <div class="faq">
        <div class="question">
            <h5>How do I return an item?</h5>
        </div>
        <div class="answer">
            <p>In the unlikely event that you need to return an item, we are here to ensure that we make this as easy as possible. If you do need to return something then simply get in touch with a member of the team and explain the problem, we can then advise on selecting the correct reason code on the returns form which is on the reverse of your invoice. All of our on the shelf items carry a 30-day risk-free guarantee (not including special or bespoke products) so just call our Customer Care Team on +44 (0)1482 620400 and we can arrange the unwanted goods to be returned to one of our depots.</p>
			<p>Covered under our guarantee are all in stock on the shelf products. Items which are made to measure, cut or adapted to your requirements are not included and all returned items should be in a saleable condition in their original packaging with all component parts accounted for.</p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>How do I return a faulty item?</h5>
        </div>
        <div class="answer">
            <p>If you purchased your item less than 30 days ago, it will be covered by our risk-free guarantee. However, if your item is faulty then please speak with our Customer Care Team on +44 (0) 1482 620400 and we can arrange the best next course of action. It is our aim to achieve 100% customer satifaction and we succeed in most instances through striving to solve our customers problems. Our first action when we hear that your item is faulty is to contact the manufacturer, we may ask for photographs to get ahead with this and start conversations early whilst we’re waiting for your item to come back to us. </p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>Can I order my delivery to another site or address?</h5>
        </div>
        <div class="answer">
            <p>Yes. In the checkout, you can specify a different address or if you’re a trade customer you can manage your address in your account.</p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>What happens if I am out when my courier comes and I miss the delivery?</h5>
        </div>
        <div class="answer">
            <p>If you miss your order you can arrange collection or delivery directly with the courier. Speak to a member of our Customer Care team if you need help with collecting your package.</p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>I have not received my item…</h5>
        </div>
        <div class="answer">
            <p>In the unlikely event that you do not receive your item within the designated time, please speak with a member of the team so we can liaise with the courier.</p>
            <p>You can speak to a member of our team on either +44 (0) 1482 620400, or email <a href="mailto:info@stonegatetooling.co.uk">info@stonegatetooling.co.uk</a> and we can contact the courier on your behalf.</p>
            <p>Our Customer Care team are available 07:00 – 16:30, Monday to Friday.</p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>Can I amend or cancel my order?</h5>
        </div>
        <div class="answer">
            <p>In the unlikely event that you do need to cancel or amend your order, speak with us immediately so we can ensure it isn’t dispatched. We hold excellent stock levels so most orders are picked and dispatched within minutes or receiving them.</p>
            <p>You can speak to a member of our team on either +44 (0) 1482 620400, or email <a href="mailto:info@stonegatetooling.co.uk">info@stonegatetooling.co.uk</a> and we can contact the courier on your behalf.</p>
            <p>Our Customer Care team are available 07:00 – 16:30, Monday to Friday.</p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>When will I receive confirmation of the order?</h5>
        </div>
        <div class="answer">
            <p>When ordering online you will receive an email confirmation and receipt once the order has been placed.</p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>Are there any products which aren’t included in the delivery options?</h5>
        </div>
        <div class="answer">
            <p>All our products can be shipped directly to you, some larger items or orders will need to be dispatched via our pallet network.</p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>Can I get delivery to outside the UK?</h5>
        </div>
        <div class="answer">
            <p>Yes. Please speak with a member of the team before ordering so we can ensure the order goes through.</p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>Can I upgrade my delivery service once the order has been dispatched?</h5>
        </div>
        <div class="answer">
            <p>Unfortunately not, once an order has been dispatched you can’t change the delivery service you originally choose.</p>
        </div>
    </div>
    <div class="faq">
        <div class="question">
            <h5>What if the goods arrive damaged?</h5>
        </div>
        <div class="answer">
            <p>No need to worry – if an item or the order is damaged in transit, speak with our Customer Care team on +44 (0) 1482 620400 who are available Monday – Friday 07:00-16:30.</p>
            <p>In most cases, we will need to collect the damaged items for quality control purposes.</p>
        </div>
    </div>
</div>
<script type="text/javascript">
    requirejs(['jquery'], function($) {
        $('.faq-container .faq').click(function() {
            if (!$(this).hasClass('active')) {
                $('.faq .answer').stop().slideUp(150);
                $('.faq').removeClass('active');
                $(this).addClass('active').find('.answer').stop().slideDown(150);
            }
        });
    });
</script>