<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Shipping Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <?= $block->getChildHtml('shipping_address') ?>

        <div id="order-shipping_method" class="admin__page-section-item quote-shipping-method">
            <?= $block->getChildHtml('shipping_method') ?>
        </div>
    </div>
</section>