<?php
$session = $block->getSession();
?>

<div id="product-review-container" data-role="product-review"></div>
<?php echo $block->getChildHtml(); ?>


<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?php /* @escapeNotVerified */
    echo $block->getProductReviewUrl(); ?>"
            }
        }
    }

</script>